### ISSUE TITLE
fun deploy 不支持迁移 nestjs 项目

### ISSUE THREAD

**Issue by JJLau626** [alibaba/funcraft#1000]
在nestjs项目下，运行 fun deploy -y 会提示
`could not detect your project framework`

**Comment by wss-git** [comment]
暂时还不支持一键迁移，可以试试这样修改
1. yml 文件 Runtime: custom
2. 新增 bootstrap 文件 ps： 这个文件需要有 可读、可写、可执行权限
![image](https://user-images.githubusercontent.com/56686088/92867525-4ff22480-f433-11ea-8012-2b70197569e9.png)
