### ISSUE TITLE
node 12 support?

### ISSUE THREAD

**Issue by ricky11** [alibaba/funcraft#1007]
Hello

Using fun for windows, I cannot create Node 12 functions?

Why not, it is possible in the console.

What is main difference between fun and fcli?

Thanks

**Comment by lisonge** [comment]
![image](https://user-images.githubusercontent.com/38517192/94571311-6ce77e00-02a2-11eb-96f6-5e28270c7aea.png)


@ricky11

**Comment by DevDengChao** [comment]
This is fixed in https://github.com/alibaba/funcraft/pull/931, please upgrade your funcraft cli.
