### ISSUE TITLE
Puppeteer依赖安装后依然报错

### ISSUE THREAD

**Issue by cc4dogman** [alibaba/funcraft#1039]
Puppeteer 5.3.1
使用fun install方式安装依赖
Funfile
RUNTIME nodejs12
RUN fun-install apt-get install ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils

执行后能够看到本地.fun文件夹内已经有了对应的so文件，但调用后直接提示
2020-11-25T09:12:38.711Z 9ff70dcd-be14-454b-89a6-4a95acfb2425 [error] [31m[1m2020-11-25T09:12:38+0000 <error> GMailRobot.js:279 (getCode) Error: Failed to launch the browser process![22m[39m
[31m[1m/mnt/robots/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory[22m[39m
[31m[1mTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md[22m[39m
[31m[1m at onClose (/mnt/robots/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)[22m[39m
[31m[1m at Interface.<anonymous> (/mnt/lazda-robots/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)[22m[39m
[31m[1m at Interface.emit (events.js:323:22)[22m[39m
[31m[1m at Interface.close (readline.js:409:8)[22m[39m
[31m[1m at Socket.onend (readline.js:187:10)[22m[39m
[31m[1m at Socket.emit (events.js:323:22)[22m[39m
[31m[1m at endReadableNT (_stream_readable.js:1204:12)[22m[39m
[31m[1m at processTicksAndRejections (internal/process/task_queues.js:84:21)[22m[39m

不知道nodejs12底层是debain版本，对应的nodejs依赖使用nas部署了，望指点下思路

**Comment by rsonghuster** [comment]
可以参考这里： https://github.com/awesome-fc/fc-puppeteer-demo
