### ISSUE TITLE
SpringBoot工程迁移后，在控制台调试httpTrigger报404

### ISSUE THREAD

**Issue by romi-liu** [alibaba/funcraft#1041]

**Comment by romi-liu** [comment]
网关中配置触发器路径无法正常出发

**Comment by wss-git** [comment]
可以加钉钉群咨询一下： 11721331

**Comment by rsonghuster** [comment]
https://help.aliyun.com/knowledge_detail/209592.html?spm=a2c4g.11186623.2.9.3e3d69achAe3Hc
