### ISSUE TITLE
fun 打包deploy程序的时候有没有类似.gitignore 的功能

### ISSUE THREAD

**Issue by wikensmith** [alibaba/funcraft#1063]
1. 整个项目文件有些不是必须的。对于go 程序，  
2. 对于win10系统， 执行fun.exe  deploy 时：Command failed: GOARCH=amd64 GOOS=linux go build -ldflags "-s -w" 执行该命令设置环境变量会出错： “'GOARCH' 不是内部或外部命令，也不是可运行的程序
或批处理文件”。这个如何处理呢？

**Comment by wss-git** [comment]
.funignore

**Comment by git-qfzhang** [comment]
> 1. 整个项目文件有些不是必须的。对于go 程序，
> 2. 对于win10系统， 执行fun.exe  deploy 时：Command failed: GOARCH=amd64 GOOS=linux go build -ldflags "-s -w" 执行该命令设置环境变量会出错： “'GOARCH' 不是内部或外部命令，也不是可运行的程序
>    或批处理文件”。这个如何处理呢？

可以参考 https://github.com/alibaba/funcraft/blob/master/docs/usage/getting_started-zh.md#funignore
