### ISSUE TITLE
fun deploy 会考虑添加yarn支持吗？

### ISSUE THREAD

**Issue by SoundShell** [alibaba/funcraft#1079]
目前 fun deploy 打包依赖是采用npm的方式，导致使用yarn的项目yarn.lock失效。

安装的依赖无法保证版本一致， 可以考虑增加对yarn的支持吗？

**Comment by rsonghuster** [comment]
你指的是 fun build 吗？  

可以直接本地使用 yarn 命令将相关依赖安装好， 再  fun deploy
