### ISSUE TITLE
fun install 安装 libjsoncpp-dev，依赖找不到

### ISSUE THREAD

**Issue by shiqiyue** [alibaba/funcraft#1103]
使用fun install安装 libjsoncpp-dev，.fun文件夹下面只有libjsoncpp.so 文件，这是个link，对应的libjsoncpp.so.1没有

**Comment by rsonghuster** [comment]
fun install --runtime python3 --package-type apt libjsoncpp-dev
我这边是正常的

![image](https://user-images.githubusercontent.com/10919599/113872265-52a8d280-97e6-11eb-9c1f-8b507c194584.png)

**Comment by shiqiyue** [comment]
我使用的runtime是java8，对应的
fun install libjsoncpp-dev --runtime java8 -p apt
![image](https://user-images.githubusercontent.com/11373492/113987683-44f45b00-9881-11eb-9574-42b27ac10129.png)

**Comment by shiqiyue** [comment]
@rsonghuster 
我现在的解决方案，是手动拷贝到/code/.fun
RUN cp -rf /usr/lib/x86_64-linux-gnu/libjsoncpp.* /code/.fun/root/usr/lib/x86_64-linux-gnu/
