### ISSUE TITLE
[BUG] Funcraft 3.6.22 部署时上传超出预期大小的压缩包

### ISSUE THREAD

**Issue by DevDengChao** [alibaba/funcraft#1105]
最近在部署函数的过程中发现 `fun` 命令行工具上传了一个 12+Mb 大小的压缩包, 我依稀记得之前还只要 400+Kb.

调试后发现 `fun` 部署时将 `.funignore` 忽略的文件以及 `package.json` 中 `devDependencies` 的开发环境依赖也进行了上传.

Ref:
+ https://connect.console.aliyun.com/connect/detail/349646
+ https://github.com/DevDengChao/aliyun-fc-issues

**Comment by liuqian1996** [comment]
`fun local start`的时候，**.funignore**生效吗？我这边不生效，还是全打进去了，我以为是正常的……

**Comment by DevDengChao** [comment]
Closed as Funcraft is deprecated.
