### ISSUE TITLE
Feature: spec支持指定tablestore以及table属性

### ISSUE THREAD

**Issue by zxkane** [alibaba/funcraft#114]
创建tablestore的时候可以指定绑定的vpc以及网络类型，希望spec支持。

https://help.aliyun.com/document_detail/55213.html?spm=a2c4g.11186623.6.566.316c4002ViYQ4N

tablestore创建table的时候支持指定文档中的属性，希望通过spec可以指定。

https://help.aliyun.com/document_detail/89939.html?spm=a2c4g.11186623.2.11.316c4002ViYQ4N#concept-z5t-jmj-bfb

**Comment by tanhe123** [comment]
Fun 已经支持 ROS 的方式进行部署。ROS 支持该功能
请参考：[开发函数计算的正确姿势 —— 使用 ROS 进行资源编排](https://yq.aliyun.com/articles/719104)
