### ISSUE TITLE
fun init 拷贝文件的时候没有区分软链接，直接把目标文件拷贝过来了

### ISSUE THREAD

**Issue by vangie** [alibaba/funcraft#162]
测试项目 https://github.com/vangie/couchbase-example

**Comment by coco-super** [comment]
此项目模版又引出另一个问题：
![image](https://user-images.githubusercontent.com/48934955/67352688-37f78500-f583-11e9-9a54-e3b287cd9143.png)
图上报错文件并不是软连接，在 chmod 的时候报错。

**Comment by tanhe123** [comment]
> 此项目模版又引出另一个问题：
> ![image](https://user-images.githubusercontent.com/48934955/67352688-37f78500-f583-11e9-9a54-e3b287cd9143.png)
> 图上报错文件并不是软连接，在 chmod 的时候报错。

这个问题已经通过 https://github.com/alibaba/funcraft/issues/642 修复了吧

这个项目 https://github.com/vangie/couchbase-example 软链接的问题由于已经更新了模板，应该也不存在这个问题了。

可以重新评估下这个任务优先级 @coco-super

**Comment by coco-super** [comment]
@tanhe123  确认了下，上述问题都已修复。此 issue 可以关闭。
