### ISSUE TITLE
Memory usage increases when receiving consecutive requests

### ISSUE THREAD

**Issue by senyuuri** [alibaba/funcraft#229]
### Background
I am writing a simple python3 function that processes an image and uploads the PDF to the OSS. The function uses a HTTP trigger.

### Issue
Tried to execute the function for a multiple times and noticed that the total memory usage gradually increased by 5MB every time (which is roughly the size of the image). Although the total memory might reduce to normal after certain execution(around 200MB), sometimes it simply shoot up to 300MB+ and exceed the quota. 

### Question
Will FC reuse a container if it receives a series of requests at the same time?

**Comment by tanhe123** [comment]
Currently, an fc instance can only process at most one request at a time.

**Comment by senyuuri** [comment]
> Currently, a fc instance can only process at most one request at a time.

Thanks for the response.I think that was a memory leak issue on my side.
