### ISSUE TITLE
fun local invoke, 挂载路径错误

### ISSUE THREAD

**Issue by giraffe-tree** [alibaba/funcraft#234]
## 起因

由于公司电脑上使用的 win7 系统, 而在 win7 上使用 docker时,  挂载路径常常出现一些奇怪的错误. 

所以我本地docker 连接的是我远程服务器(centOS)上的 docker daemon

## 错误

当我调用 `fun local invoke` 时, 出现以下错误

```shell
$ fun local invoke -e input.txt helloworld
ENOENT: no such file or directory, lstat 'D:\root\2019\May\fc\helloworld\fc-demo                           .jar'
```

我的远程路径是 `/root/2019/May/fc/helloworld/fc-demo.jar.`

## 版本

```
$ fun --version
2.14.0
```

**Comment by tanhe123** [comment]
可以尝试使用最新版本再试一下，如果还有问题，欢迎提新的 issue。
