### ISSUE TITLE
nas_brwoser 本地运行调试：目录内容变更问题

### ISSUE THREAD

**Issue by git-qfzhang** [alibaba/funcraft#259]
example/nas_browser利用fun loacl start在终端1启动后，在终端2运行./nas.sh cp file fc:/mnt/nas，成功传输了本地文件file，但nas_browser目录被检测到发生变化，于是终端1提示detect code changes，报错信息如下图所示，
![image](https://user-images.githubusercontent.com/52195264/60081127-cb4eb400-9763-11e9-9513-01ea796daae4.png)
此时进程会被关闭，需要重启后再使用。
目录内容变更检测可以据此进行相应修改。

**Comment by tanhe123** [comment]
推荐使用 [fun nas](https://yq.aliyun.com/articles/712700) 功能
