### ISSUE TITLE
Windows 平台下 deploy 时 node_modules 目录下的 junction 处理问题

### ISSUE THREAD

**Issue by karoyqiu** [alibaba/funcraft#261]
在 Windows 下 deploy 后 node_modules 目录下的 junction 到了 Linux 下全变成了指向不存在的 Windows 下路径的软链接，导致 require 时找不到路径。

比如，在 Windows 下存在一个 junction：

    C:\Users\xxxxx\source\repos\xxxxx\node_modules> dir
    2019/06/20  09:08    <JUNCTION>     tablestore [C:\Users\xxxxx\source\repos\xxxxx\node_modules\_tablestore@4.3.2@tablestore]

deploy 后就会发现在 Linux 下 tablestore 软链接指向了 `C:\Users\xxxxx\source\repos\xxxxx\node_modules\_tablestore@4.3.2@tablestore`，而不是 `./_tablestore@4.3.2@tablestore` 或相对应的绝对路径。

**Comment by tanhe123** [comment]
1. 我们测试使用 npm 安装后，其实并不会生成 junction 软链接，你这里提供的这个软链接是自己手动创建的吗？
2. 这里 Fun 的行为是正确的，因为如果是软链接，那就把这个软链接本身打包进来（不会修改原来的指向）。如果软链接是你手动创建的，可以在创建时，指定相对路径。

**Comment by tanhe123** [comment]
没有重现这个问题，先关掉，有疑问，可以重新提个 issue。
