### ISSUE TITLE
Windows10 使用fun local invoke image-crawler错误

### ISSUE THREAD

**Issue by j5465** [alibaba/funcraft#263]
[开发函数计算的正确姿势 —— 爬虫](https://yq.aliyun.com/articles/672624)
跟着这篇文章走到
`fun local invoke image-crawler`
时装载错误
```
skip pulling image aliyunfc/runtime-python2.7:1.5.3...
(HTTP code 400) unexpected - invalid mount config for type "bind": invalid mount path: 'C:/Users/zhaox/Desktop/projects/Win32Com/code' mount path must be absolute
```

`fun --version
`
`2.15.0`

**Comment by tanhe123** [comment]
请确认下，docker 的配置里是否勾选了 “C 盘” 呢？

**Comment by j5465** [comment]
@tanhe123 

查了查不知道怎么看，
`docker info
`

> Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.131-boot2docker
Operating System: Boot2Docker 18.09.7 (TCL 8.2.1)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 989.4MiB
Name: ali
ID: XWKD:MM7H:XEEB:T5GV:AWHW:VRUX:T737:A32D:XMYT:APHM:E4NM:CXTD
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://xxxxxxxx.mirror.aliyuncs.com/
Live Restore Enabled: false
Product License: Community Engine

`C:\Users\zhaox\.docker\machine\machines\ali\config.json`
的信息

> {
    "ConfigVersion": 3,
    "Driver": {
        "IPAddress": "192.168.99.100",
        "MachineName": "ali",
        "SSHUser": "docker",
        "SSHPort": 56372,
        "SSHKeyPath": "C:\\Users\\zhaox\\.docker\\machine\\machines\\ali\\id_rsa",
        "StorePath": "C:\\Users\\zhaox\\.docker\\machine",
        "SwarmMaster": false,
        "SwarmHost": "tcp://0.0.0.0:3376",
        "SwarmDiscovery": "",
        "VBoxManager": {},
        "HostInterfaces": {},
        "CPU": 1,
        "Memory": 1024,
        "DiskSize": 20000,
        "NatNicType": "82540EM",
        "Boot2DockerURL": "",
        "Boot2DockerImportVM": "",
        "HostDNSResolver": false,
        "HostOnlyCIDR": "192.168.99.1/24",
        "HostOnlyNicType": "82540EM",
        "HostOnlyPromiscMode": "deny",
        "UIType": "headless",
        "HostOnlyNoDHCP": false,
        "NoShare": false,
        "DNSProxy": true,
        "NoVTXCheck": false,
        "ShareFolder": ""
    },
    "DriverName": "virtualbox",
    "HostOptions": {
        "Driver": "",
        "Memory": 0,
        "Disk": 0,
        "EngineOptions": {
            "ArbitraryFlags": [],
            "Dns": null,
            "GraphDir": "",
            "Env": [],
            "Ipv6": false,
            "InsecureRegistry": [],
            "Labels": [],
            "LogLevel": "",
            "StorageDriver": "",
            "SelinuxEnabled": false,
            "TlsVerify": true,
            "RegistryMirror": [
                "https://xxxxxxxx.mirror.aliyuncs.com"
            ],
            "InstallURL": "https://get.docker.com"
        },
        "SwarmOptions": {
            "IsSwarm": false,
            "Address": "",
            "Discovery": "",
            "Agent": false,
            "Master": false,
            "Host": "tcp://0.0.0.0:3376",
            "Image": "swarm:latest",
            "Strategy": "spread",
            "Heartbeat": 0,
            "Overcommit": 0,
            "ArbitraryFlags": [],
            "ArbitraryJoinFlags": [],
            "Env": null,
            "IsExperimental": false
        },
        "AuthOptions": {
            "CertDir": "C:\\Users\\zhaox\\.docker\\machine\\certs",
            "CaCertPath": "C:\\Users\\zhaox\\.docker\\machine\\certs\\ca.pem",
            "CaPrivateKeyPath": "C:\\Users\\zhaox\\.docker\\machine\\certs\\ca-key.pem",
            "CaCertRemotePath": "",
            "ServerCertPath": "C:\\Users\\zhaox\\.docker\\machine\\machines\\ali\\server.pem",
            "ServerKeyPath": "C:\\Users\\zhaox\\.docker\\machine\\machines\\ali\\server-key.pem",
            "ClientKeyPath": "C:\\Users\\zhaox\\.docker\\machine\\certs\\key.pem",
            "ServerCertRemotePath": "",
            "ServerKeyRemotePath": "",
            "ClientCertPath": "C:\\Users\\zhaox\\.docker\\machine\\certs\\cert.pem",
            "ServerCertSANs": [],
            "StorePath": "C:\\Users\\zhaox\\.docker\\machine\\machines\\ali"
        }
    },
    "Name": "ali"
}

**Comment by tanhe123** [comment]
看起来，您使用的是 docker toolbox，这个官方已经不维护了。建议您使用 docker for windows 再试一下
