### ISSUE TITLE
InactiveError问题

### ISSUE THREAD

**Issue by ericluwj** [alibaba/funcraft#28]
![image](https://user-images.githubusercontent.com/1736023/39823834-7eb29a34-53e0-11e8-8b47-6fe026d0e678.png)
只是试一下hello world例子 API Gateway 设置却失败 到底是什么问题？

**Comment by JacksonTian** [comment]
API网关没有开通服务。

**Comment by vangie** [comment]
先去apigateway控制台开通服务

Thanks
Vangie

在 2018年5月9日，下午11:32，Eric Lu <notifications@github.com<mailto:notifications@github.com>> 写道：


[image]<https://user-images.githubusercontent.com/1736023/39823834-7eb29a34-53e0-11e8-8b47-6fe026d0e678.png>
只是试一下hello world例子 API Gateway 设置却失败 到底是什么问题？

**Comment by JacksonTian** [comment]
我们需要改进一下 该错误提示。

**Comment by ericluwj** [comment]
其实API网关已经开通服务 而是RAM服务还没开通。
一开通RAM服务就搞定了。
