### ISSUE TITLE
[Java]fun local star报错Invalid status code: undefined

### ISSUE THREAD

**Issue by drewxiuxiuxiu** [alibaba/funcraft#287]
如图, 代码就是最简单的helloworld. deploy到云上一切正常.

![image](https://user-images.githubusercontent.com/46234308/61937509-9a130f00-afc1-11e9-991f-ce3fb1b50dad.png)

之后服务便停掉了. 代码出错抛出异常反而能得到Http Response, 且服务不会死掉. 猜测是代码中哪些地方没有正确设置http的status code.

**Comment by tanhe123** [comment]
https://github.com/alibaba/funcraft/pull/323
