### ISSUE TITLE
当依赖特别多的时候显示超时无法正常上传

### ISSUE THREAD

**Issue by heartshuai** [alibaba/funcraft#31]
RequestTimeoutError: PUT http://1925300965708640.cn-beijing.fc.aliyuncs.com/2016-08-15/services/fc/functions/helloworld timeout(60000).
 PUT http://1925300965708640.cn-beijing.fc.aliyuncs.com/2016-08-15/services/fc/functions/helloworld failed.
    at Timeout.setTimeout [as _onTimeout] (/usr/local/nodejs/node-v8.9.4-linux-x64/lib/node_modules/@alicloud/fun/node_modules/_httpx@2.1.2@httpx/lib/index.js:110:17)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

**Comment by vangie** [comment]
@heartshuai 能把您的依赖列表给一下么？我们测试一下。

**Comment by heartshuai** [comment]
我就是npm install update 进行安装的依赖

**Comment by JacksonTian** [comment]
@vangie 我们的创建函数 在处理 文件大于 50MB 时，确实非常慢。

**Comment by JacksonTian** [comment]
@heartshuai 请尽量控制依赖的大小。

**Comment by chenqinga** [comment]
意思是大于50MB就不能上传吗，还是说可以上传就是速度慢，请详细说一下

**Comment by JacksonTian** [comment]
慢。

**Comment by JacksonTian** [comment]
我打算这么优化下这个问题：
- [ ] 提供 OSS 时，使用 OSS 来中转，也就是先上传至 OSS，在创建或者更新函数。
  - [ ] 当文件大于某个指时，分片上传指 OSS，再合并
- [ ] 如果无 OSS，保持现有方案。

**Comment by GitNiko** [comment]
不能通过解析require反向依赖的node_modules再上传吗，这样应该能减小很多

**Comment by tanhe123** [comment]
如下建议都可以尝试：

1. 通过 fun config 将超时时间设置的长一些
2. 通过 fun package 将依赖上传 oss 
3. 通过 nas 存储不经常变动的依赖，避免每次都上传
4. 使用 webpack 打包

具体的操作方法，请参考 README 里的帮助文档。如果还有问题，欢迎提新的 issue
