### ISSUE TITLE
fun更新到2.15.2之后deploy报错

### ISSUE THREAD

**Issue by mela93** [alibaba/funcraft#315]
## npm -g 全局安装
```
+ @alicloud/fun@2.15.2
added 438 packages from 400 contributors in 22.957s
```
## 运行 fun deploy 报错
```
$ fun deploy
Cannot find module 'fs-extra'
Require stack:
- /usr/local/lib/node_modules/@alicloud/fun/lib/nas.js
- /usr/local/lib/node_modules/@alicloud/fun/lib/fc.js
- /usr/local/lib/node_modules/@alicloud/fun/lib/deploy/deploy-by-tpl.js
- /usr/local/lib/node_modules/@alicloud/fun/lib/commands/deploy.js
- /usr/local/lib/node_modules/@alicloud/fun/bin/fun-deploy.js
```
## fun版本
```
$ fun --version
2.15.2
```
## 操作系统
```
$ sw_vers                                  
ProductName:    Mac OS X
ProductVersion: 10.15
BuildVersion:   19A526h
```

**Comment by mela93** [comment]
更新: fun v2.15.1 没问题

**Comment by tanhe123** [comment]
感谢反馈，今天会发个 2.16.0，会一起修复这个问题

**Comment by tanhe123** [comment]
> ### 更新: fun v2.15.1 没问题
> ## 手动安装修复
> ```
> cd /usr/local/lib/node_modules/@alicloud/fun
> npm install
> ```
> 
> ## 再次运行 fun deploy 依旧报错
> ```
>         Waiting for function functionName to be deployed...
>                 Waiting for packaging function functionName code...
> fs.js:126
>     throw err;
>     ^
> 
> Error: EMFILE: too many open files, open '/usr/local/lib/node_modules/@alicloud/fun/lib/exception-handler.js'
>     at Object.openSync (fs.js:447:3)
>     at Object.readFileSync (fs.js:349:35)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:22)
>     at Module.load (internal/modules/cjs/loader.js:643:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
>     at Module.require (internal/modules/cjs/loader.js:683:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at process.<anonymous> (/usr/local/lib/node_modules/@alicloud/fun/lib/visitor.js:31:3)
>     at process.emit (events.js:203:13)
>     at processPromiseRejections (internal/process/promises.js:201:33) {
>   errno: -24,
>   syscall: 'open',
>   code: 'EMFILE',
>   path: '/usr/local/lib/node_modules/@alicloud/fun/lib/exception-handler.js'
> }
> ```

您的这个问题是您的系统有最大文件打开数的限制，请参考：https://github.com/alibaba/funcraft/issues/77#issuecomment-416290858

**Comment by mela93** [comment]
@tanhe123 
感谢您的及时回复，不过 2.15.1  `fun deploy` 都是正常的，没有出现过这个错误。

> 您的这个问题是您的系统有最大文件打开数的限制，请参考：[#77 (comment)](https://github.com/alibaba/funcraft/issues/77#issuecomment-416290858)

**Comment by mela93** [comment]
`Cannot find module 'fs-extra'`
fixed on: v2.16.0

**Comment by mela93** [comment]
最后发现问题是：不小心把@alicloud/fun也安装到要deploy的函数计算文件夹node_modules下导致packages过多超出限制。移除后实际1千多个packages。
