### ISSUE TITLE
希望支持更新MNSTopic Event的自动化配置部署

### ISSUE THREAD

**Issue by DrizzleRisk** [alibaba/funcraft#316]
如果在template.yml中配置MNSTopic的Event，则只能部署一次，再次部署会报错。
目前的解决方案是需要手工在控制台先把已有的MNS触发器删除，然后再进行发布，比较麻烦。
希望支持更新MNSTopic Event的自动化配置部署。

**Comment by coco-super** [comment]
@DrizzleRisk 
1. 使用 Fun  部署，定义了 mns 触发器时不支持更新操作，多次部署时只会出现 warning 日志，再次部署无影响。
2. Fun 也支持直接创建 MNS 服务，更完整的示例请[参考](https://github.com/alibaba/funcraft/tree/master/examples/mnsTopic-trigger)。假如你 template.yml 中定义了 mns 触发器以及 mns 服务，第一次部署时成功。第二次部署时，如果创建主题的属性与已经存在的主题属性相同，只会返回个状态码（402）。所以多次部署时没有问题。第三次部署时，假如你修改了 mns 服务中 properties 的属性，此时会报错 mns topic name 已经存在，此时的报错是符合预期的。
