### ISSUE TITLE
fun install 错误

### ISSUE THREAD

**Issue by l616769490** [alibaba/funcraft#318]
执行：fun install
skip pulling image registry.cn-beijing.aliyuncs.com/aliyunfc/runtime-python3.6:build-1.5.5...
Task => [UNNAMED]
     => PYTHONUSERBASE=\code\.fun\python pip install --user PyMySQL
ERROR: Could not install packages due to an EnvironmentError: [Errno 22] Invalid argument: '\\code\\.fun\\python'

undefined
----------------
平台：win10
----------------
另外此次更新的版本调试特别慢，经常是发了请求要等十多秒再调试才行，否则就提示端口未打开

**Comment by abersheeran** [comment]
我也是

**Comment by tanhe123** [comment]
感谢反馈，调试慢的问题，本周我们会发个版本修复

**Comment by l616769490** [comment]
> 感谢反馈，调试慢的问题，本周我们会发个版本修复

无法导入第三方包的问题请尽快解决，不管是单个导入还是一起导入都不行。以下是单个导入的报错：
fun install --save --runtime python3 --package-type pip PyMySQL
skip pulling image registry.cn-beijing.aliyuncs.com/aliyunfc/runtime-python3.6:build-1.5.5...
Cannot read property '#<Object>' of undefined

**Comment by abersheeran** [comment]
> 感谢反馈，调试慢的问题，本周我们会发个版本修复

调试慢这个不急，先把安装依赖的问题解决了。
我跟上面那位一样，python3环境下什么包都装不上。一样的报错。

**Comment by tanhe123** [comment]
好的，预计这周会发版本修复，麻烦先使用 2.15.2，应该是不存在这个问题的

**Comment by l616769490** [comment]
> 好的，预计这周会发版本修复，麻烦先使用 2.15.2，应该是不存在这个问题的

退回去也是一样的了，甚至把docker和nodejs都卸载了再装2.15.2都还是一样的。

**Comment by tanhe123** [comment]
https://github.com/alibaba/funcraft/pull/327

**Comment by tanhe123** [comment]
https://github.com/alibaba/funcraft/pull/324

**Comment by tanhe123** [comment]
这两个问题应该都修复了，麻烦升级到最新版本，如果依旧有问题，麻烦新开个 issue
