### ISSUE TITLE
工具时而报错时而成功

### ISSUE THREAD

**Issue by heartshuai** [alibaba/funcraft#32]

**Comment by heartshuai** [comment]
![image](https://user-images.githubusercontent.com/33921414/40155988-5e14482e-59c9-11e8-855f-f1b331e454a5.png)

**Comment by heartshuai** [comment]
@JacksonTian

**Comment by heartshuai** [comment]
![image](https://user-images.githubusercontent.com/33921414/40173208-a300fb64-5a03-11e8-8499-a6e793b84036.png)
200次的上传有四次失败

**Comment by tanhe123** [comment]
请使用最新版本测试下，如果依旧有问题，欢迎再次提 issue
