### ISSUE TITLE
The instruction for Docker installation should be updated

### ISSUE THREAD

**Issue by denverdino** [alibaba/funcraft#320]
https://github.com/alibaba/funcraft/blob/master/docs/usage/installation-zh.md

It is suggested to install Docker Desktop for Mac/Windows, rather than the Docker toolbox any more

**Comment by tanhe123** [comment]
We always recommend docker for Mac/Windows. 

The help link here is `http://mirrors.aliyun.com/docker-toolbox/windows/docker-for-windows/beta/`, although the path contains `docker-toolbox`, it is indeed a `docker for Windows` installation package.

**Comment by denverdino** [comment]
That is incorrect. It should install Docker Desktop/Docker CE through

https://hub.docker.com/search/?type=edition&offering=community

**Comment by tanhe123** [comment]
There are some issue if we recommend user to download docker from `https://hub.docker.com/search/?type=edition&offering=community`:

1. Must log in. But most users do not have a docker account
2. Download speed is too slow
3. There are some issues which is not fixed on windows

The docker version we recommend in our [documentation](https://github.com/alibaba/funcraft/blob/master/docs/usage/installation-zh.md) have been already tested on Windows.

**Comment by tanhe123** [comment]
However, your provided document is still good, we will consider adding it to the document for advanced users to choose.
