### ISSUE TITLE
Should we change fun to pull Docker images from Alibaba Cloud Registry Service?

### ISSUE THREAD

**Issue by denverdino** [alibaba/funcraft#321]
It is helpful to improve the performance for the image pulling

**Comment by tanhe123** [comment]
We have added this feature in the 2.16.0 version. 

The current strategy deciding whether to use `Alibaba Cloud Registry Service` or `Docker Hub` depends on whether you can ping `google.com`.

Do you mean that we should use the `Alibaba Cloud Registry Service` by default?

**Comment by tanhe123** [comment]
https://github.com/alibaba/funcraft/pull/324
