### ISSUE TITLE
本地调试断点竟然会停在注释行和空白行

### ISSUE THREAD

**Issue by l616769490** [alibaba/funcraft#325]
我用fun对一个函数进行调试，断点竟然一步一步停在了被注释的行上，然后还进入被注释掉的方法里执行了。我删除了注释的行，结果断点停在了空白行，再点下一步又进入了刚才那个方法执行。由于2.16.1这个版本BUG这么多，而且回退倒2.15.2都不行了，是不是image有问题，能否有办法把fun和image都回退到2.15.2的版本去？

[https://86lvyou.oss-cn-shanghai.aliyuncs.com/img/funerror1.png?Expires=1565277582&OSSAccessKeyId=TMP.hVBttwLupKENEBZSKMQ6nEJv5G2MuU4ayC3GskZSuVLtg83wTG2VmXJYQvLVgK6w5HE8W6QxP7PZvziHBJLHfQj5tFt9CwmEFVHbnqdP6mUPwasyLaaBRH46BEQh9b.tmp&Signature=fkbybA9%2B9KM6dFHB%2BvSQuYEL1%2Bc%3D](url)
[https://86lvyou.oss-cn-shanghai.aliyuncs.com/img/funerror2.png?Expires=1565277932&OSSAccessKeyId=TMP.hVBttwLupKENEBZSKMQ6nEJv5G2MuU4ayC3GskZSuVLtg83wTG2VmXJYQvLVgK6w5HE8W6QxP7PZvziHBJLHfQj5tFt9CwmEFVHbnqdP6mUPwasyLaaBRH46BEQh9b.tmp&Signature=DBLvy1lOtmvNW26KNpP%2BeVAyhMQ%3D](url)

**Comment by vangie** [comment]
一般来说如果断点的行位置不对应是因为运行的程序和源码不对应导致的。

**Comment by tanhe123** [comment]
如果没有更多反馈，这个 issue 就先关闭了。

如果此问题依旧存在，可以新建 issue 反馈。
