### ISSUE TITLE
在Windows上 Fun install 400错误

### ISSUE THREAD

**Issue by abersheeran** [alibaba/funcraft#331]
```
(HTTP code 400) unexpected - invalid mount config for type "bind": bind source path does not exist: /mnt/c/Users/AberS/Documents/Coding/71tui/serverless/login
```

在 WSL 上执行 `fun install` 出现这个错误。

题外话：作为商业产品，软件发布之前就没有在流行的几个操作系统平台上测试过？我从用你们这个 fun 开始，就没运行成功过。三个版本了，一次都没能正常 fun install 过。是真的逼我司转投腾讯云吗？

**Comment by tanhe123** [comment]
WSL 暂未适配，目前 windows，支持比较好的是 docker for windows，请参考：https://github.com/alibaba/funcraft/blob/master/docs/usage/installation-zh.md

**Comment by abersheeran** [comment]
Docker 我是装在 Windows 下的，WSL就是借个命令的壳。刚刚查了一下 WSL 下的 bind 需要去除路径前的 `/mnt` ，建议修复。

我在 WSL 里执行的原因是因为 在 Windows 下， docker pull 会不等到执行完成直接返回。必须手动 pull 才能拉取镜像。请问这又是什么原因呢？

**Comment by abersheeran** [comment]
我直接下了最新版的 exe 到 Windows上，发现能用了！那么目前看来，只有上面那一个 pull 问题需要解决了。

**Comment by tanhe123** [comment]
可以先手动使用 docker pull，成功后，fun 会跳过 pull 的过程，然后看下后续的操作是否有问题。感谢反馈。

**Comment by abersheeran** [comment]
刚刚试了试，手动 pull 之后没有发现其他问题。

**Comment by tanhe123** [comment]
https://github.com/alibaba/funcraft/issues/380
