### ISSUE TITLE
fun下载第三方包的镜像地址设置

### ISSUE THREAD

**Issue by l616769490** [alibaba/funcraft#346]
使用fun下载python的镜像，似乎不是从官方镜像下载的，有时候pypi更新了一两天了，fun才能下载到最新的版本。我可以自己设置下载源吗？

**Comment by tanhe123** [comment]
目前没有特别好的方法配置。

只能手动修改，并将镜像名以及 tag 配置的与 fun 一致才可以。

比如，可以手动 docker run --rm -it xxxxxxx bash 进入，更改源，然后 docker commit，然后配置相同的 tag。
