### ISSUE TITLE
不依赖于 node.js 的 fun 安装/版本管理

### ISSUE THREAD

**Issue by abersheeran** [alibaba/funcraft#352]
😊 写了一个脚本方便在没有安装 node.js 的电脑上管理 fun 的版本

https://github.com/abersheeran/autofun

**Comment by vangie** [comment]
@abersheeran 方便搞一个 windows 下的包管理器 choco 么？https://chocolatey.org

比如在 mac 下，我们可以使用 homebrew

```
$ brew tap vangie/formula
$ brew install fun
```

**Comment by abersheeran** [comment]
这个应该需要官方去弄。不过感觉意义不大，chocolatey 并不是 Windows 钦定的，为了装个 fun 再去弄个包管理器在电脑上，好像不太好。

**Comment by tanhe123** [comment]
感谢反馈，其他用户如果有类似需求可以参考。我这里先把 issue close 掉了。有任何问题，欢迎开新的 issue。
