### ISSUE TITLE
pkg 打包后，docker pull 在 windows 上会直接退出

### ISSUE THREAD

**Issue by tanhe123** [alibaba/funcraft#380]
![image](https://user-images.githubusercontent.com/4676235/63925205-3d04f000-ca7c-11e9-80ad-e50fe772a5d4.png)

**Comment by tanhe123** [comment]
如果用户遇到这个问题，可以先根据提示，手动执行 docker pull 来解决

**Comment by abersheeran** [comment]
17 天了，这个问题啥时候能修复？
