### ISSUE TITLE
docker pull 镜像如果磁盘没有空间，没有提示错误信息

### ISSUE THREAD

**Issue by tanhe123** [alibaba/funcraft#408]
现在使用 Fun 的时的错误如下：
![image](https://user-images.githubusercontent.com/4676235/64663600-f9988180-d47e-11e9-9eac-1992bec42edf.png)

如果使用提示的 docker 命令 pull 镜像提示如下：
![image](https://user-images.githubusercontent.com/4676235/64663672-28aef300-d47f-11e9-922c-263beec424e1.png)

希望能像原生 docker 命令一样，提示详细的报错信息。

**Comment by coco-super** [comment]
Mac 下通过调整 docker 设置的 disk image size 压满磁盘，并不会出现上述问题。同时 fun local invoke| start 命令会抛出正确错误提示：
`failed to register layer: Error processing tar file(exit status 1): write /usr/lib/x86_64-linux-gnu/libopencv_ocl.a: no space left on device`

Windows 下 60G 不好重现，推测问题发生在 Windows 上，或者操作存在特殊情况。

**Comment by tanhe123** [comment]
暂时不支持这个场景
