### ISSUE TITLE
如何在VSCode中获取Python的代码提示

### ISSUE THREAD

**Issue by abersheeran** [alibaba/funcraft#420]
使用 fun install 安装完包之后，由于并不是一个完整的Python环境被保存在项目里。VSCode的Python插件没办法识别，我看了docker的运行情况，也没有容器在运行，不能用 remote container。
所以我该如何获取代码提示？

**Comment by tanhe123** [comment]
您先试下，将 fun install 安装的包，使用 pip install xxx 在宿主机上也安装一下。

**Comment by abersheeran** [comment]
那 fun 的意义岂不是就剩下一键部署了。😓

**Comment by ChanDaoH** [comment]
如果您是用 vscode 编写代码的话，可以麻烦截图下工作目录吗？可以通过配置获得代码提示的

**Comment by abersheeran** [comment]
![image](https://user-images.githubusercontent.com/25364828/64931493-79ea2880-d86b-11e9-9552-cbac323e65b4.png)

我目前的解决方案是用 pipenv 装个虚拟环境在项目里。但这么干没办法保持环境一致，我的本地是3.7，你们的镜像是 3.6。有时候我可能不知不觉的就用了 3.7 的一些东西导致 3.6 里没法跑。

**Comment by ChanDaoH** [comment]
之前有尝试通过 [vscode 插件](https://marketplace.visualstudio.com/items?itemName=aliyun.aliyun-serverless) 创建 python 函数并选择引用 runtime 内置 lib 吗？如果有的话可以看下 workspace 根目录下的 .env 文件，里面有配置 PYTHONPATH。
![image](https://user-images.githubusercontent.com/19430792/64931657-84f18880-d86c-11e9-8dbc-36719ad7e674.png)
如果没有的话，可以自己手动创建一个 .env 文件，里面配置下 PYTHONPATH

**Comment by abersheeran** [comment]
你们居然还写了个 VSCode 插件。我去试试，没啥问题我就 Close 这个 ISSUE。

**Comment by abersheeran** [comment]
嗯。装了插件之后，我没看到任何指引，配了 .env 也不行。
而且我试着用插件运行了一下函数，又回到了那个 windows 下没办法 pull 你们镜像的问题。
哈哈哈，我还是手动来吧 @ChanDaoH

**Comment by ChanDaoH** [comment]
指引需要在插件面板点击创建函数才会出现，可以看下 [README](https://github.com/alibaba/serverless-vscode)。
配置了 .env 后需要重启 vscode。
pull 镜像失败了？可以手动 pull 下

**Comment by abersheeran** [comment]
这个 README 我看了。重启过了，没用。我老老实实用 pipenv 好了。
我觉得这个 pull 问题才是最重要的吧……

**Comment by ChanDaoH** [comment]
pull 失败的截图麻烦贴一下 @tanhe123 win 下 pull 镜像失败的问题麻烦有空跟进下哈

**Comment by abersheeran** [comment]
他之前发过一个 issue #380 ，里面有的。

而且就算他更新了也没用，你们这个插件用的版本是旧版本的 fun ，好像是 1.9 吧。

**Comment by abersheeran** [comment]
啊，sorry，我看错了。

**Comment by abersheeran** [comment]
不水了，我接着搬砖。你们加油。
