### ISSUE TITLE
fun 在 mac 上检测 docker shared 路径不准确的问题

### ISSUE THREAD

**Issue by tanhe123** [alibaba/funcraft#421]
我在 docker File Sharing 上配置了一项 /Applications，使用 fun local 后，提示：

```
Please add directory '/Applications/xxxx' to Docker File sharing list, more information please refer to https://github.com/alibaba/funcraft/blob/master/docs/usage/faq-zh.md
```

现在的逻辑是去 '$HOME/Library/Group Containers/group.com.docker/settings.json' 下查询 defaultFileSharingPaths 配置，但是在我的配置里，并没有这个，而是下面这个：

```
  "filesharingDirectories" : [
    "/Applications",
    "/Users",
    "/Volumes",
    "/builds",
    "/private",
    "/tmp"
  ]
```

**Comment by git-qfzhang** [comment]
我看了一下，我的配置中当前也是 filesharingDirectories，而不是 defaultFileSharingPaths，明天去看下其他人电脑上这个配置属性是什么，然后进行相应修改

**Comment by tanhe123** [comment]
需要分别看下安装完成时，以及修改后这两个场景，有肯能是这两个场景对应的配置是不同的
