### ISSUE TITLE
questionOfDefinitionInFunSantax

### ISSUE THREAD

**Issue by shifeichen** [alibaba/funcraft#440]
link: https://apigateway.console.aliyun.com

we found that there is not definition of "Basic Returned Results Definition" in fun template file sample,for example, i want to insert content like this:
{
    "isBase64Encoded":true|false,
    "statusCode":httpStatusCode,
    "headers":{response headers},
    "body":""
}

so i don't know how to solve the problem, please help.

**Comment by coco-super** [comment]
`apigw_fc:
    Type: 'Aliyun::Serverless::Api'
    Properties:
      StageName: RELEASE
      DefinitionBody:
        '/python/hello':
          get:
            x-aliyun-apigateway-api-name: pythonhello
            x-aliyun-apigateway-fc:
              arn: acs:fc:::services/${pythondemo.Arn}/functions/${hello.Arn}/

            x-aliyun-apigateway-request-parameters:
              - apiParameterName: 'token'
                location: 'Path'
                parameterType: 'String'
                required: 'REQUIRED'
            
            x-aliyun-apigateway-auth-type: 'APPOPENID'
            x-aliyun-apigateway-open-id-connect-config:
              idTokenParamName: 'token'
              openIdApiType: 'BUSINESS'
            x-aliyun-apigateway-force-nonce-check: false
            x-aliyun-apigateway-app-code-auth-type: HEADER_QUERY
            x-aliyun-apigateway-allow-signature-method: HmacSHA256
            x-aliyun-apigateway-disable-internet: true
            x-aliyun-apigateway-websocket-api-type: REGISTER
            x-aliyun-apigateway-result-type: PASSTHROUGH

            x-aliyun-apigateway-result-sample: result sample
            x-aliyun-apigateway-fail-result-sample: failed samples

            x-aliyun-apigateway-error-code-sample:
              - code: 400
                message: error
                description: error description
              - code: 300
                message: error
                description: error description`

**Comment by coco-super** [comment]
@shifeichen 
![image](https://user-images.githubusercontent.com/48934955/65313644-4ab71c80-dbc7-11e9-88e8-42e485a3b300.png)

**Comment by coco-super** [comment]
apigw_fc:
    Type: 'Aliyun::Serverless::Api'
    Properties:
      StageName: RELEASE
      DefinitionBody:
        '/python/hello':
          get:
            x-aliyun-apigateway-api-name: pythonhello
            x-aliyun-apigateway-fc:
              arn: acs:fc:::services/${pythondemo.Arn}/functions/${hello.Arn}/
            x-aliyun-apigateway-request-parameters:
              - apiParameterName: 'token'
                location: 'Path'
                parameterType: 'String'
                required: 'REQUIRED'
            x-aliyun-apigateway-auth-type: 'APPOPENID'
            x-aliyun-apigateway-open-id-connect-config:
              idTokenParamName: 'token'
              openIdApiType: 'BUSINESS'
            x-aliyun-apigateway-force-nonce-check: false
            x-aliyun-apigateway-app-code-auth-type: HEADER_QUERY
            x-aliyun-apigateway-allow-signature-method: HmacSHA256
            x-aliyun-apigateway-disable-internet: true
            x-aliyun-apigateway-websocket-api-type: REGISTER
            x-aliyun-apigateway-result-type: PASSTHROUGH

            x-aliyun-apigateway-result-sample: result sample
            x-aliyun-apigateway-fail-result-sample: failed samples

            x-aliyun-apigateway-error-code-sample:
              - code: 400
                message: error
                description: error description
              - code: 300
                message: error
                description: error description

**Comment by tanhe123** [comment]
如果还有问题，可以提新的 issue，这个先关掉了
