### ISSUE TITLE
fun config 能否内化到项目内？

### ISSUE THREAD

**Issue by abersheeran** [alibaba/funcraft#446]
我之前一直使用公司的账号去开发部署项目，最近几天为了造自己的小轮子切到了自己的阿里云账号。
结果今天改公司代码，怎么推都推不上去，过了一个下午才想起来账号登陆的是自己的。

fun 的账号能不能像 git 一样，可以设置全局的，但是也允许在项目内设置？

**Comment by tanhe123** [comment]
现在支持的。
请参考：https://github.com/alibaba/funcraft/blob/master/docs/usage/getting_started-zh.md#配置的优先级

**Comment by abersheeran** [comment]
好的。感谢。
