### ISSUE TITLE
Windows 上调试时 ctrl + c 停止进程后docker 容器不会 stop，需手动 docker stop

### ISSUE THREAD

**Issue by coco-super** [alibaba/funcraft#467]
mac 上正确效果：
![image](https://user-images.githubusercontent.com/48934955/65751942-57df8880-e13e-11e9-8d55-b1afe001e028.png)

**Comment by abersheeran** [comment]
这是 docker for windows 的问题。docker 容器在 windows 没办法用 ctrl+c 去终止。

**Comment by coco-super** [comment]
`docker.js` 中 `waitingForContainerStopped` 中的 SIGINT 收到了，但是，fun 没有等待全部的容器停止，就被杀掉了。

**Comment by tanhe123** [comment]
https://github.com/alibaba/funcraft/issues/668
