### ISSUE TITLE
Python环境新增fun.yaml依赖后fun install不生效

### ISSUE THREAD

**Issue by linfan** [alibaba/funcraft#469]
在python环境里修改了fun.yaml之后，重新fun install始终不生效。
比如在fun.yaml里增加了一行`pip: flask==1.1.1`依赖：
![image](https://user-images.githubusercontent.com/1113435/65761265-0c82a580-e151-11e9-9b52-e1fdd6ae6f5e.png)
重新执行fun install，始终是 Using cache，在 .fun 目录里的依赖也没有新增的flask：
![image](https://user-images.githubusercontent.com/1113435/65761386-4653ac00-e151-11e9-83c3-e5ddbbec9fa7.png)

**Comment by linfan** [comment]
fun版本：3.0.2

**Comment by tanhe123** [comment]
fun.yml 在 fun 3.0 后升级成了 Funfile：https://yq.aliyun.com/articles/719100

您可以在您当前的目录下找到一个名为 Funfile 的文件，然后添加您的依赖

**Comment by tanhe123** [comment]
如果依旧有问题，可以提新的 issue
