### ISSUE TITLE
fun init生成的Java模板项目构建报错

### ISSUE THREAD

**Issue by linfan** [alibaba/funcraft#470]
使用 fun init 模板创建的Java HTTP Trigger项目，未经修改，使用`mvn clean package`构建通过：
![image](https://user-images.githubusercontent.com/1113435/65764098-6b4b1d80-e157-11e9-85b0-e4918323624d.png)

使用`fun build`构建报错：
![image](https://user-images.githubusercontent.com/1113435/65763986-24f5be80-e157-11e9-9ee7-03fbf041b350.png)

**Comment by linfan** [comment]
fun版本：3.0.2

**Comment by tanhe123** [comment]
3.0 版本我们引入了 Fun Build，希望提供更好的体验。在这个 demo 的 README 里面有具体用法，您也可以阅读这篇帮助文档：https://yq.aliyun.com/articles/719102

**Comment by tanhe123** [comment]
如果有问题，可以提新的 issue 反馈
