### ISSUE TITLE
fun local 在 Jenkins 里的问题

### ISSUE THREAD

**Issue by abersheeran** [alibaba/funcraft#471]
![image](https://user-images.githubusercontent.com/25364828/65810599-e1df2e00-e1de-11e9-9558-4fd241c73191.png)

这种情况如何解决？

**Comment by tanhe123** [comment]
没有安装 docker？

**Comment by abersheeran** [comment]
有 docker 啊。第一步我就检查了 docker 版本😂

**Comment by tanhe123** [comment]
主要是看下 docker 有没有启动，使用 docker ps 看下

**Comment by abersheeran** [comment]
😂果然没启动。我问了下，不能在Jenkins里起docker。但是可以用指定镜像作为流水线环境。
你们有没有相关的文档？就是在你们的镜像里，由用户手动执行测试工作。
