### ISSUE TITLE
Fun deploy项目后在网页端无法看见部分文件夹

### ISSUE THREAD

**Issue by yekesit511** [alibaba/funcraft#480]
为什么用Fun deploy后我其他的文件夹都不见了呢。但是程序依旧是可以正常进行的，下载下来的代码也是有的。只是在web端看不到。。。
![Screen Shot 2019-10-03 at 11 50 15](https://user-images.githubusercontent.com/55303465/66155220-00c13400-e5d4-11e9-9f7d-3254d95ab8f0.png)

**Comment by yekesit511** [comment]
这个图怎么不见了。。我再弄一下
![Screen Shot 2019-10-10 at 11 17 48](https://user-images.githubusercontent.com/55303465/66675545-5f149500-ec1a-11e9-8312-1221ba4f05b0.png)
![Screen Shot 2019-10-10 at 11 19 53](https://user-images.githubusercontent.com/55303465/66675553-6176ef00-ec1a-11e9-82cd-51489ea9255b.png)

**Comment by muxiangqiu** [comment]
代码可以提供一下吗？方便加一下钉钉群吗，官方钉钉群：11721331

**Comment by yekesit511** [comment]
我加了。 请问你的昵称是啥呢。。我怎么圈你

**Comment by muxiangqiu** [comment]
我的昵称是木香丘

**Comment by 502647092** [comment]
我也遇到了这个问题
可以下载上传
但是WebIDE里面看不到

**Comment by muxiangqiu** [comment]
原因是新版 fun 底层依赖的打包压缩库换了，导致打包出来的格式和以前的有些不一样（但是打包结果是没有问题的），导致控制台编辑器对这种格式不能正确识别，控制台编辑器已经修复该问题
