### ISSUE TITLE
就算只修改了个别函数，fun deploy service命令也会重新上传所有代码？

### ISSUE THREAD

**Issue by nestattacked** [alibaba/funcraft#487]
我修改了一个函数的代码，然后执行fun deploy service，其他没有修改的函数的代码似乎也被重新上传了

想问下本来就是这么设计的么，我的版本是3.0.1

**Comment by vangie** [comment]
函数会被打包成 zip 再上传。您这边用的是什么 runtime，代码很大么？

**Comment by nestattacked** [comment]
不大，就是觉得有点奇怪。如果本来就是这样的话，那就没事了。

**Comment by coco-super** [comment]
@nestattacked 
![image](https://user-images.githubusercontent.com/48934955/66728673-e19a9000-ee78-11e9-8a9f-92656ab7dcd8.png)

**Comment by coco-super** [comment]
@nestattacked 
看起来你使用的命令是: `fun deploy serviceName`，行为是上传 yml 中 service 下的 所有 function。
如果你只想上传一个函数，请使用命令` fun deploy functionName`， 或者 `fun deploy serviceName/functionName`
ps: 如果使用 fun deploy functionName 时，yml 中不同 service 下的相同 functionName，fun 会交互询问您要 deploy 的函数，例如：

`? Select a function? (Use arrow keys)
❯ cdn-test-service/cdn-test-function 
  cdn-test-service1/cdn-test-function `

其他命令细节 `fun deploy -h`:
![image](https://user-images.githubusercontent.com/48934955/66728686-f545f680-ee78-11e9-972f-59cbb11043f4.png)
