### ISSUE TITLE
如何区分本地模拟开发环境和部署环境？

### ISSUE THREAD

**Issue by 1006079161** [alibaba/funcraft#494]
本地开发的时候，难免会使用本地的一些测试资源,比如mysql等等，而发布到线上，使用另一个mysql地址
我需要在settings里进行判断是本地模拟环境还是线上环境来进行逻辑开发
请问本地模拟环境有什么特别的标志可以证明是本地开发环境！！！！！！！

**Comment by tanhe123** [comment]
请参考[这篇文章](https://yq.aliyun.com/articles/672623)里面的“环境变量”与“ Credentials”章节：
![image](https://user-images.githubusercontent.com/4676235/66472939-db936080-eac0-11e9-9786-db7530e33055.png)
