### ISSUE TITLE
在使用fun deploy部署demo的过程中，报错。

### ISSUE THREAD

**Issue by txd12** [alibaba/funcraft#497]
在使用fun deploy部署demo的过程中，收到错误信息：GET /services/demo2 failed with 400. requestid: undefined, message: undefined.
![image](https://user-images.githubusercontent.com/50935943/66548991-ec051300-eb74-11e9-9edd-0fb2f660e751.png)

**Comment by tanhe123** [comment]
这个是因为 accountId 非法，但是提示的错误看起来有些问题
