### ISSUE TITLE
fun deploy 好像不会忽略.funignore里配置的文件

### ISSUE THREAD

**Issue by 502647092** [alibaba/funcraft#522]
如题
![image](https://user-images.githubusercontent.com/10203793/66822236-6919f900-ef76-11e9-9fa7-d03b802f1b7d.png)
![image](https://user-images.githubusercontent.com/10203793/66822315-95ce1080-ef76-11e9-9663-d5eb5f4bd3fc.png)
我想只上传运行必须的文件
忽略源码和配置文件

顺带问下 deploy的Npm Install是在容器启动的时候执行的 
还是 直接把本地的node_modules上传了

**Comment by coco-super** [comment]
@502647092 
您的截图里貌似没有看到 .funIgnore 文件，尝试下把它放在 template.yml 同级试下？
`fun deploy` 会将 codeUri 执向的目录打包成 .zip 上传到函数计算。

**Comment by 502647092** [comment]
![image](https://user-images.githubusercontent.com/10203793/66895818-38919800-f026-11e9-94ed-c6f7b23677d3.png)

**Comment by tanhe123** [comment]
fun build 将项目代码复制到 .fun/build/artifacts 目录下，应该考虑 funignore，这里没有考虑，应该是个问题，这个我们 fix 下就好了。

另外，看您的项目，使用的是 nodejs，并不强制要求 build，您可以将 .fun/build 目录删除，然后每次使用 fun install 就可以了

**Comment by 502647092** [comment]
好 我试一下

**Comment by 502647092** [comment]
@tanhe123 我用Build的原因是
开发环境有很多不需要的库和文件
build的环境是只有运行需要的文件
所以要把开发和运行的分开
或者 函数计算有没有那种 推送之后自动安装依赖的功能

**Comment by tanhe123** [comment]
> @tanhe123 我用Build的原因是
> 开发环境有很多不需要的库和文件
> build的环境是只有运行需要的文件
> 所以要把开发和运行的分开
> 或者 函数计算有没有那种 推送之后自动安装依赖的功能

ok，理解您的问题了，build 其实也是为这种场景设计的，那等我们修完这个问题您可以继续使用。

另外，如果您是未来了避免不需要的依赖，可以通过 webpack 打包：https://yq.aliyun.com/articles/701714

**Comment by coco-super** [comment]
#534

**Comment by tanhe123** [comment]
麻烦重新试下，如果还有问题，可以反馈给我们

**Comment by 502647092** [comment]
已经可以了 没什么问题
