### ISSUE TITLE
python runtime log 以及 print 都没有输出的问题

### ISSUE THREAD

**Issue by tanhe123** [alibaba/funcraft#526]

**Comment by tanhe123** [comment]
https://github.com/alibaba/funcraft/issues/509

**Comment by tanhe123** [comment]
再补充一个使用场景：

logging.basicConfig(level=logging.INFO, filename="/tmp/fc_instance.log", format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)
logger.info('initializing')

**Comment by coco-super** [comment]
1.  针对 python runtime，`print("xxxx")` 无法输出的问题 https://github.com/aliyun/fc-docker/pull/45 已经修复。
2.  python logging 的默认级别为 INFO，若想输出 debug 日志参照：
`import logging
def handler(event, context):
    logger = logging.getLogger()
    logger.setLevel(logging.DEBUG)
    logger.debug('hello world')`

**Comment by coco-super** [comment]
> 再补充一个使用场景，用户看不到日志输出：
> 
> ```python
> logging.basicConfig(level=logging.INFO, filename="/tmp/fc_instance.log", format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
> logger = logging.getLogger(__name__)
> logger.info('initializing')
> ```
用户在线上通过这种方式是可以正确输出日志，但在本地 invoke 无法输出。

**Comment by tanhe123** [comment]
> > 再补充一个使用场景，用户看不到日志输出：
> > ```python
> > logging.basicConfig(level=logging.INFO, filename="/tmp/fc_instance.log", format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
> > logger = logging.getLogger(__name__)
> > logger.info('initializing')
> > ```
> 
> 用户在线上通过这种方式是可以正确输出日志，但在本地 invoke 无法输出。

上面这种线上应该也不支持，如果要自定义，可以：

```python
# -*- coding: utf-8 -*-
import logging

logger = logging.getLogger()
logger.handlers = []

def handler(event, context):
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    logger = logging.getLogger(__name__)
    logger.info('This is a log info')

    return "ok"
```

推荐还是最好使用默认的logger， 信息完整
