### ISSUE TITLE
升级3.0.6后报invalid reference format错误

### ISSUE THREAD

**Issue by l616769490** [alibaba/funcraft#532]
begin pulling image registry.cn-beijing.aliyuncs.com/aliyunfc/runtime-python3.6:1.6.6, you can also use 'docker pull registry.cn-beijing.aliyuncs.com/aliyunfc/runtime-python3.6:1.6.6'
to pull image by yourself.
1.6.6: Pulling from aliyunfc/runtime-python3.6
Digest: sha256:3cc963719bfb0f06f58004c195e2866acc20f9b3dad72b19ab918c11e1fe4783
Status: Image is up to date for registry.cn-beijing.aliyuncs.com/aliyunfc/runtime-python3.6:1.6.6
(HTTP code 500) server error - invalid reference format

**Comment by coco-super** [comment]
你的环境是 windows？，docker 的版本是？确认下挂载的路径是否在 docker setting 的共享文件夹中。

**Comment by tanhe123** [comment]
如果还有问题，可以提新的 issue
