### ISSUE TITLE
bootstrap没有执行权限

### ISSUE THREAD

**Issue by gohopo** [alibaba/funcraft#533]
在windows环境下使用custom runtime,用fun deploy打包,
代码包中bootstrap没有执行权限,访问报错
```
{
"ErrorCode": "InternalServerError",
"ErrorMessage": "an internal error has occurred. Please retry."
}
```
工作人员反馈说是`exec /code/bootstrap时permission denied`,没有可执行权限.

**Comment by coco-super** [comment]
https://github.com/alibaba/funcraft/pull/536 修复了 linux 上的权限问题。
windows 上的权限暂时还不支持。

**Comment by coco-super** [comment]
fun 2.16.5 及之前版本中 windows 权限有保留。证明可解，需要调研下。
2.16.5 之前用的是 JSZip 之后用的是 Archiver

**Comment by tanhe123** [comment]
对于 custom runtime，可以先考虑针对 bootstrap 这个文件，强行添加执行权限
