### ISSUE TITLE
fun local 如何使用本地环境变量

### ISSUE THREAD

**Issue by 502647092** [alibaba/funcraft#535]
fun local start 好像不支持命令行上的环境变量

**Comment by tanhe123** [comment]
环境变量是要配置在这里才可以的：https://github.com/alibaba/funcraft/blob/master/docs/specs/2018-04-03-zh-cn.md#环境变量对象

**Comment by 502647092** [comment]
> 环境变量是要配置在这里才可以的：[https://github.com/alibaba/funcraft/blob/master/docs/specs/2018-04-03-zh-cn.md#环境变量对象](https://github.com/alibaba/funcraft/blob/master/docs/specs/2018-04-03-zh-cn.md#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E5%AF%B9%E8%B1%A1)

配置到这里之后 上传的时候会覆盖线上的
我是想 本地运行的时候使用一套
上传的时候另一套

**Comment by shiny** [comment]
同样的问题，希望本地使用测试的key，线上使用生产环境的key
