### ISSUE TITLE
关于浏览器 CORS 请求的 http trigger 的配置

### ISSUE THREAD

**Issue by shd101wyy** [alibaba/funcraft#545]
你好，

我现在正在尝试配置 CORS。当我在浏览器中发送带有 `Authorization` 的 Header 时候，浏览器会进行 `preflight` 检查并且发送 `OPTIONS` 的方法请求。但是由于现阶段阿里云 serverless 的 http trigger 不支持 OPTIONS 导致 `preflight` 会一直失败所以 CORS 请求也失败。  
请问有没有什么解决方案呢？

谢谢

**Comment by tanhe123** [comment]
下个版本发布后，就可以正式使用了，

正式发布前，可以通过 npm install -g alibaba/funcraft 直接从源码安装使用。
