### ISSUE TITLE
fun local 支持自定义路由

### ISSUE THREAD

**Issue by chenjun1011** [alibaba/funcraft#549]
目前通过 fun local 进行本地调试，预览地址是基于函数名来生成的：  http://localhost:8000/2016-08-15/proxy/ssr-demo/home/

而在 Web 单页应用场景下，我们需要去匹配路由，渲染对应的页面。基于上面的预览路径，由于 path 并不是对应真实路由规则，所以本地预览很难将链路串联起来。

理想的形式，可能是我们在本地也能配置一个路由和函数的映射规则，方便调试。

**Comment by vangie** [comment]
@chenjun1011 您这边有配合使用函数计算的自定义域名功能么？自定义域名可以把路径去掉，有映射路由和规则的能力，只是目前 fun local 还没有支持。 

还有一个选择是 api gateway。

**Comment by chenjun1011** [comment]
@vangie  嗯，上面两种方案可以解决上线后的问题。

目前主要的诉求，是希望 fun local 也能提供路由配置能力，方便在本地开发阶段调试路由相关问题。

**Comment by a9udn9u** [comment]
给有这个需求的人作为参考：@tanhe123 的merge之后，template.yaml里自定义域名的路径映射可以使用了，比如`localhost:8000/proxy/[service]/[function]`可以用`localhost:8000/[your mapped path]`访问。这个在`fun local start`的命令行提示里有，但是文档里没有。（希望可以加进文档）
在`/etc/hosts`里可以把你自己的域名映射到`localhost`，这样本地就可以用你的域名:端口号/自定义path测试了。
