### ISSUE TITLE
(HTTP code 500) server error - invalid reference format

### ISSUE THREAD

**Issue by ranmc** [alibaba/funcraft#555]
H:\Project\Fun-service\fun-demo>fun install sbox -f fun-demo -i
using template: template.yml
begin pulling image registry.cn-beijing.aliyuncs.com/aliyunfc/runtime-java8:build-1.6.7, you can also use 'docker pull registry.cn-beijing.aliyu
ncs.com/aliyunfc/runtime-java8:build-1.6.7' to pull image by yourself.
build-1.6.7: Pulling from aliyunfc/runtime-java8
Digest: sha256:49699398d0db4a99f0a574d6c7f717dc5bd22ef4ab9faf7148eaa0c92b6fa6f8
Status: Image is up to date for registry.cn-beijing.aliyuncs.com/aliyunfc/runtime-java8:build-1.6.7
(HTTP code 500) server error - invalid reference format 
![捕获](https://user-images.githubusercontent.com/32739812/67455627-c68e0400-f660-11e9-8de6-7682d1910a72.PNG)
![捕获1](https://user-images.githubusercontent.com/32739812/67455632-cd1c7b80-f660-11e9-88eb-e09b645a336e.PNG)
![捕获2](https://user-images.githubusercontent.com/32739812/67455639-d0b00280-f660-11e9-8a30-c7fc5adaf2df.PNG)

**Comment by coco-super** [comment]
https://github.com/alibaba/funcraft/issues/380

**Comment by coco-super** [comment]
目前 fun 的行为是： 从各个 repo 下载的 Image 都将 rename 为标准的 ImageName。`ex`: `registry.cn-beijing.aliyuncs.com/aliyunfc/runtime-python2.7:1.6.8` 将会 rename 为 `aliyunfc/runtime-python2.7:1.6.8`。

导致问题的原因： dockerode api 中 tag 接口抛出。
部分用户并没有此问题发生，所以推测：各用户的 docker 版本相对较高（大版本至少 19.x.x)，tag 接口会自动处理解析。问题稳定重现在 `docker verison` : `17.03.0-ce`。具体 work 的版本未知，此处不做进一步测试。
