### ISSUE TITLE
invalid signature: 0x8074b50

### ISSUE THREAD

**Issue by coco-super** [alibaba/funcraft#557]
![image](https://user-images.githubusercontent.com/48934955/67546174-403ff380-f72e-11e9-8092-19da8066e1a8.png)

**Comment by coco-super** [comment]
windows 和 mac 都I稳定重现。 fun 版本 3.0.8，但是用源码跑就可以避开这个问题...

**Comment by coco-super** [comment]
已确定是 unzipper 的问题，`0.10.5` 版本的 bug。`fun` 下个版本将会降为 `0.10.4` 为其修复。

**Comment by tanhe123** [comment]
目前，只发现了该用户的 jar 包有问题。我们自行 mvn package 打的 jar 是没问题的。

针对该用户的 jar，发现，只有使用 unzipper 0.10.5 时有问题

**Comment by coco-super** [comment]
用户 fun 3.0.8，打包用的是 maven 版本 3.5.4
