### ISSUE TITLE
docker 版本 1.13.1，使用 fun install 也有问题

### ISSUE THREAD

**Issue by tanhe123** [alibaba/funcraft#563]
![image](https://user-images.githubusercontent.com/4676235/67770823-19692080-fa92-11e9-8d8e-37ca9e9aec6c.png)

**Comment by tanhe123** [comment]
这里，只设置了 fun local 相关功能进行提示，目前看起来，其他的与 docker 相关的命令也会有问题，https://github.com/alibaba/funcraft/issues/463

**Comment by tanhe123** [comment]
建议是，测试一个可用的最低版本，然后当不满足时，直接报错，提示更新

**Comment by coco-super** [comment]
> 建议是，测试一个可用的最低版本，然后当不满足时，直接报错，提示更新

最低可用版本为 `17.03.0-ce`,低于此版本直接报错，提示更新。
