### ISSUE TITLE
Fun nas sync 不指定 service 时，应该提示出默认的 sync service 是哪一个

### ISSUE THREAD

**Issue by vangie** [alibaba/funcraft#572]
查看 fun local invoke 的效果。提示出来，可以帮忙用户及早的发现问题。

![image](https://user-images.githubusercontent.com/1388582/67999085-cc559c00-fc95-11e9-8d2a-bda229949ab5.png)
![9D4F4410-BFA4-4801-8E0D-ECDAB6B3B330](https://user-images.githubusercontent.com/1388582/67999101-dd061200-fc95-11e9-881c-b8f6b024af48.png)

上图的情况也不应该报错，而是提前报错没有找到 nas 配置之类的。

**Comment by CNqfzhang** [comment]
fun nas sync 时候不指定 service 时候会同步所有配置了 NasConfig 的 service，图中的报错 "UserId of undefined" 已经在 https://github.com/alibaba/funcraft/pull/574 中修复，麻烦有空 review 一下
