### ISSUE TITLE
如何运行 Python 第三方库的可执行文件？

### ISSUE THREAD

**Issue by abersheeran** [alibaba/funcraft#585]
https://github.com/miyakogi/pyppeteer#usage

例如上面链接给出的 pyppeteer，在 `fun-install pip install pyppeteer` 之后，需要再运行 `pyppeteer-install`。但是像下面这么写，`fun install`就会失败。

```
RUNTIME python3

WORKDIR /code

RUN fun-install pip install pyppeteer
RUN .fun/python/bin/pyppeteer-install
RUN fun-install pip install flask

COPY . /code
```

报错如下：

![image](https://user-images.githubusercontent.com/25364828/68522476-b6c02200-02e6-11ea-9981-3ce4e8d5d8f0.png)

这些玩意都被安装去哪了？

**Comment by tanhe123** [comment]
```
RUNTIME python3

WORKDIR /code

RUN fun-install pip install pyppeteer
RUN PYTHONUSERBASE=/code/.fun/python PYPPETEER_HOME=/code .fun/python/bin/pyppeteer-install
RUN fun-install pip install flask
```

可以这样执行，执行完成后，会在代码目录生成 local-chromium 目录，里面有 chromium。

这个变量值 PYPPETEER_HOME 可以参考这里：https://github.com/miyakogi/pyppeteer/blob/1aa0221f4fda21d59b18373e0f09071f2cd7402b/docs/reference.md#environment-variables
