### ISSUE TITLE
执行 ./bin/fun-nas.js cp -r srcPath dstPath 在程序中源宿地址顺序相反问题

### ISSUE THREAD

**Issue by CNqfzhang** [alibaba/funcraft#602]
执行 ./bin/fun.js nas cp -r srcPath dstPath 或 ./bin/fun-nas.js cp -r srcPath dstPath 时，传入程序的源地址值为 dstPath，传入的目的地址值 为 srcPath，即源宿地址顺序相反。
执行 ./bin/fun.js nas cp  srcPath dstPath -r 或 ./bin/fun-nas.js cp srcPath dstPath -r 时，程序运行正常。
-n 选项与 -r 选项有相同的问题。
执行 ./bin/fun-nas-cp.js 时无输入参数问题，即运行正常。

**Comment by coco-super** [comment]
此问题 commander 已经修复。
