### ISSUE TITLE
macOS Catalina无法composer install

### ISSUE THREAD

**Issue by muyuto** [alibaba/funcraft#616]
近期更新系统至macos Catalina后相关软件也有所更新
当前环境 
本地composer 1.9.1 
Docker version 19.03.5, build 633a0ea

按fc官方指导，在函数本地目录中添加composer.json后执行composer install --no-dev报错
$ composer install --no-dev
Loading composer repositories with package information
Updating dependencies

Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
zlib_decode(): data error
https://mirrors.aliyun.com/composer could not be fully loaded, package information was loaded from the local cache and may be out of date

**Comment by tanhe123** [comment]
您试下 fun install -d 是否可以呢？
