### ISSUE TITLE
fun  nas 在 windows 上打包时的权限丢失。

### ISSUE THREAD

**Issue by coco-super** [alibaba/funcraft#621]
![image](https://user-images.githubusercontent.com/48934955/69413608-1ccb9100-0d4c-11ea-9024-8f046dd871f7.png)

**Comment by coco-super** [comment]
错误： `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: spawn EACCES`

**Comment by tanhe123** [comment]
导致的问题是，如果在 windows 上 npm、apt 安装了依赖，如果包含权限，则部署上去后调用，会提示没有执行权限的问题

**Comment by 1006079161** [comment]
我发现windows环境下即使设置成everyone 权限全选，也是不能继承权限，目前只能在linux进行777操作，希望能尽快支持windows

**Comment by tanhe123** [comment]
> 我发现windows环境下即使设置成everyone 权限全选，也是不能继承权限，目前只能在linux进行777操作，希望能尽快支持windows

收到，感谢反馈

**Comment by tanhe123** [comment]
已经修复了，可以升级最新 fun 版本体验。如果还有问题，可以新建 issue
