### ISSUE TITLE
欠费时，部署 nas 时的报错并不表意

### ISSUE THREAD

**Issue by coco-super** [alibaba/funcraft#626]
账号欠费时应该检测到错误关键字，提示用户可能由欠费导致的.......
`{"ErrorCode":"InvalidArgument","ErrorMessage":"Mount NFS://36939484ce-yne69.cn-shanghai.nas.aliyuncs.com:/ command failed with exit code = -1, please make sure that the nas mount point address is correct and is accessible from the service VPC"}`

**Comment by tanhe123** [comment]
这个 fun 这边没办法处理，因为 nas 的报错都一样。现在 FC 已经将 nas 的报错返回出来了，不需要 Fun 修复了
