### ISSUE TITLE
fun install --runtime python3 --package-type apt --save imagemagick 安装失败

### ISSUE THREAD

**Issue by vangie** [alibaba/funcraft#628]
```
fun install --runtime python3 --package-type apt --save imagemagick
begin pulling image registry.cn-beijing.aliyuncs.com/aliyunfc/runtime-python3.6:build-1.7.2, you can also use 'docker pull registry.cn-beijing.aliyuncs.com/aliyunfc/runtime-python3.6:build-1.7.2' to pull image by yourself.
build-1.7.2: Pulling from aliyunfc/runtime-python3.6
Digest: sha256:55341a82275beab21e4fffe9abac3f17f23b25ccb0553a9e9020305d517da901
Status: Image is up to date for registry.cn-beijing.aliyuncs.com/aliyunfc/runtime-python3.6:build-1.7.2
Task => AptTask
     => apt-get update (if need)
     => apt-get install -y -d -o=dir::cache=/code/.fun/tmp/install imagemagick --reinstall
     => bash -c
        for f in $(ls /code/.fun/tmp/install/archives/*.deb); do
          echo "Preparing to unpack ${f##*/}"
          dpkg -x $f /code/.fun/root;

          echo "Setting up ${f##*/}"
          mkdir -p /code/.fun/tmp/install/deb-control/${f%.*};
          dpkg -e $f /code/.fun/tmp/install/deb-control/${f%.*};
          if [ -f "/code/.fun/tmp/install/deb-control/${f%.*}/postinst" ]; then
            FUN_INSTALL_LOCAL=true DPKG_MAINTSCRIPT_NAME=postinst /code/.fun/tmp/install/deb-control/${f%.*}/postinst configure;
          fi;
        done;
Preparing to unpack imagemagick_8%3a6.8.9.9-5+deb8u18_amd64.deb
Setting up imagemagick_8%3a6.8.9.9-5+deb8u18_amd64.deb
update-alternatives: error: alternative path /code/.fun/root/usr/bin/compare-im6 doesn't exist
undefined

save package install commnad to /Users/vangie/Desktop/test/Funfile
```

**Comment by coco-super** [comment]
`imagemagick` 是系统安装的，为什么还要手动装载呢？

**Comment by coco-super** [comment]
`imagemagick` 是系统安装的，为什么还要手动装载呢？

**Comment by coco-super** [comment]
`imagemagick` 是系统安装的，为什么还要手动装载呢？
报错的具体原因是：提取 deb 包( dpkg -e )时，`/code/.fun/root/usr/bin/compare-im6` 软链指向 `../lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16/compare`，指向的实际文件不存在。
安装 `imagemagick-6.q16` 后正常工作，即软连接的真实指向存在。
![image](https://user-images.githubusercontent.com/48934955/69617131-bd82bf00-1072-11ea-8350-3edc8ad03efd.png)

**Comment by vangie** [comment]
> `imagemagick` 包是系统安装的，为什么还要手动装载呢？

这句话啥意思，imagemagic 系统内置了么？

**Comment by vangie** [comment]
> 安装 `imagemagick-6.q16` 后正常工作，即软连接的真实指向存在。

报错了，怎么安装下去呢？

**Comment by coco-super** [comment]
imagemagick 的问题进一步追踪到：
apt-get 下载 deb 到目录，不是只下载了一个 deb 如果有依赖会下载多个 deb 的前提是 原 packge 依赖的包 不存在。
所以 针对 imagemagick 做了测试：由于内置了 imagemagick ，且 依赖包存在于系统。所以 fun install 不会下载依赖包，只下载一个原 package 到目录。也就是说此时不存在 deb 包排序问题。

**Comment by fatalfeel** [comment]
its a real bad problem take a lot time resolve. here is answer
git clone --recursive https://github.com/ImageMagick/ImageMagick6.git

gedit ~/ImageMagick6/Makefile.in
#find section install-binPROGRAMS: $(bin_PROGRAMS)
-e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
#change to
-e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/-im6/' | \

cd ~/ImageMagick6
./configure --prefix=/usr
make install

#done!
