### ISSUE TITLE
能否支持更高级的队列功能

### ISSUE THREAD

**Issue by hooklife** [alibaba/funcraft#636]
MNS 的触发器是不是没有事务的功能，只能保证消息被消费，但是没办法保证消息被消费成功。
如果是这样的话，我觉得这个功能就完全没有意义了，还不如用sdk invoke 一下 function
是否应该出一个支持更高级的队列的触发器？

**Comment by rsonghuster** [comment]
**MNS 的触发器是不是没有事务的功能，只能保证消息被消费，但是没办法保证消息被消费成功。**
A： MNS 触发源保证异步函数调用成功， 但是不能保证这个函数的逻辑消费信息成功，所以我的理解是您的函数逻辑能保证消息消费成功即可

**是否应该出一个支持更高级的队列的触发器？**
A： 需要等 mns 或者 mq 的 queue 支持 http endpoint 功能

**Comment by hooklife** [comment]
> **MNS 的触发器是不是没有事务的功能，只能保证消息被消费，但是没办法保证消息被消费成功。**
> A： MNS 触发源保证异步函数调用成功， 但是不能保证这个函数的逻辑消费信息成功，所以我的理解是您的函数逻辑能保证消息消费成功即可
> 
> **是否应该出一个支持更高级的队列的触发器？**
> A： 需要等 mns 或者 mq 的 queue 支持 http endpoint 功能

1.如果函数的逻辑需要调用外部接口 或者查询数据库之类的操作，肯定不能保证函数的逻辑一定能消费成功，但是 MNS 有没有其他重试的策略，和传统的队列相比需要多处理很多东西。

2.如果没有高级的队列功能很多现有的应用程序就不能整套的迁移过来，很多应用都有队列的东西，而且都需要重试机制，这一点 lambada可以直接集成 sqs 就很好用。

**Comment by rsonghuster** [comment]
1. 重试策略：https://help.aliyun.com/document_detail/27481.html?spm=a2c4g.11186623.2.23.4d503bdbaNVYzT

2. 这个建议很好， 我们推动解决， 请关注我们官网群哈

**Comment by tanhe123** [comment]
这个 issue 先在 fun 这边 close 了，如果还有问题可以提工单或者到官网群里反馈
