### ISSUE TITLE
好像还不支持dotnetcore2.1

### ISSUE THREAD

**Issue by philwu** [alibaba/funcraft#644]
https://github.com/alibaba/funcraft/blob/a71df1addac091309f54329a88904c2820893c61/lib/docker-opts.js#L26-L35

好像还不支持dotnetcore2.1
有计划吗？

**Comment by 1006079161** [comment]
你可以使用 --runtime custom 自定义镜像，部署的时候以独立依赖部署即可

**Comment by tanhe123** [comment]
已经支持
