### ISSUE TITLE
电脑是deepin系统，本地测试函数时候如何传参？

### ISSUE THREAD

**Issue by phpsxg** [alibaba/funcraft#647]
本地测试时候，测试函数时候我是点击这个按钮，如何模拟
![1](https://user-images.githubusercontent.com/19278211/69937972-045f3180-1517-11ea-8ba0-296c4ed217c1.png)
传参数呢？

**Comment by ChanDaoH** [comment]
这个是直接 Python 的插件直接运行当前文件吧？您这边可以安装一下 [FC VSCode 插件](https://github.com/alibaba/serverless-vscode/) 来进行调试 (支持自定义传参)，或者手动用 `fun local invoke` 功能通过 `-e, --event` 参数，指定事件文件

**Comment by phpsxg** [comment]
> 这个是直接 Python 的插件直接运行当前文件吧？您这边可以安装一下 [FC VSCode 插件](https://github.com/alibaba/serverless-vscode/) 来进行调试 (支持自定义传参)，或者手动用 `fun local invoke` 功能通过 `-e, --event` 参数，指定事件文件

我已经安装fc vscode插件了，请问在哪里自定义参数？

**Comment by ChanDaoH** [comment]
![image](https://user-images.githubusercontent.com/19430792/69940509-75a1e300-151d-11ea-8b5f-aec3ecaee72a.png)

点击图中的按钮，会在 Teminal 输出调用命令，修改命令中的 Event 文件路径中的内容即可

![image](https://user-images.githubusercontent.com/19430792/69940590-9ff3a080-151d-11ea-9dba-ef2c0d3013b7.png)

**Comment by phpsxg** [comment]
> ![image](https://user-images.githubusercontent.com/19430792/69940509-75a1e300-151d-11ea-8b5f-aec3ecaee72a.png)
> 
> 点击图中的按钮，会在 Teminal 输出调用命令，修改命令中的 Event 文件路径中的内容即可
> 
> ![image](https://user-images.githubusercontent.com/19430792/69940590-9ff3a080-151d-11ea-9dba-ef2c0d3013b7.png)
![深度截图_选择区域_20191202161251](https://user-images.githubusercontent.com/19278211/69941441-d382fa80-151e-11ea-8ce8-048b22c0a182.png)

请问右键函数计算install package和start sandbox代表什么意思，我点击了start sandbox然后安装一堆东西
再次执行此函数时候，报错如下：
![2](https://user-images.githubusercontent.com/19278211/69942100-412f2680-151f-11ea-8793-1d2a9a965240.png)

**Comment by ChanDaoH** [comment]
start sandbox 是启动沙箱环境用于安装倚赖的，退出沙箱环境再点击函数执行就可以

**Comment by phpsxg** [comment]
> start sandbox 是启动沙箱环境用于安装倚赖的，退出沙箱环境再点击函数执行就可以

好的，谢谢您
