### ISSUE TITLE
fun deploy --use-ros 服务名包含下划线时创建角色出错

### ISSUE THREAD

**Issue by vangie** [alibaba/funcraft#674]
```
StackValidationFailed: resources.fc_mysqlRole: Property error: fc_mysqlRole.Properties.RoleName: mysql-test-fc_mysqlRole-A56028C58E52 is invalid. It is up to 64 characters. 

Deploy failed, you can login to https://ros.console.aliyun.com/#/stack/cn-shanghai to see deploy logs.
```

![image](https://user-images.githubusercontent.com/1388582/70976014-095edc00-20e6-11ea-9d13-98649e43d4df.png)

**Comment by coco-super** [comment]
ROS 已经改进了，Fun 不需要修复了

**Comment by vangie** [comment]
![image](https://user-images.githubusercontent.com/1388582/77394029-57683780-6dd9-11ea-9778-09e28bc850fb.png)

**Comment by coco-super** [comment]
函数计算服务名可以有下划线，所以服务名有下划线, 自动生成的 role 应该把下划线转换掉，例如转换成 '-'，
