### ISSUE TITLE
如何进行函数间的调用

### ISSUE THREAD

**Issue by ZhanYishu** [alibaba/funcraft#706]

**Comment by coco-super** [comment]
@ZhanYishu  您说的是本地吗？

**Comment by ZhanYishu** [comment]
> @ZhanYishu 您说的是本地吗？

本地或者线上，感觉服务端渲染是要通过访问公网获取不同函数的web后台数据

**Comment by coco-super** [comment]
> > @ZhanYishu 您说的是本地吗？
> 
> 本地或者线上，感觉线上服务端渲染是要通过访问公网获取不同函数的web后台数据

线上可以通过 sdk 访问普通函数。如果是要访问的函数是 http，可以通过公网或内网都可以访问到。
本地 可以参照： https://www.yuque.com/docs/share/ed8ab4cf-1a76-4bbf-910b-c48efbd340e8?#

**Comment by ZhanYishu** [comment]
> > > @ZhanYishu 您说的是本地吗？
> > 
> > 
> > 本地或者线上，感觉线上服务端渲染是要通过访问公网获取不同函数的web后台数据
> 
> 线上可以通过 sdk 访问普通函数。如果是要访问的函数是 http，可以通过公网或内网都可以访问到。
> 本地 可以参照： https://www.yuque.com/docs/share/ed8ab4cf-1a76-4bbf-910b-c48efbd340e8?#

感谢
