### ISSUE TITLE
请问如何通过命令行import远程函数或者是服务到本地

### ISSUE THREAD

**Issue by Tarocch1** [alibaba/funcraft#717]

**Comment by coco-super** [comment]
支持 vscoce 插件以及控制台。

**Comment by coco-super** [comment]
@Tarocch1  目前只支持控制台下载或者 vscode 插件 import 到本地。fun 目前不支持的。

**Comment by vangie** [comment]
@Tarocch1 请问您在什么场景下有这个需求？

**Comment by Tarocch1** [comment]
@vangie 主要是vscode的插件不好用，我这里publish不上去，所以我想直接用命令行。但是一边用插件import，一边用命令行publish又很奇怪，所以我想看看能不能用命令行import。

**Comment by tanhe123** [comment]
publish 不上去，可以把遇到的问题反馈下。

另外，也可以使用控制台导出到本地。

**Comment by tanhe123** [comment]
这个问题先 close 了，如果还有问题，麻烦建立新的 issue。
