### ISSUE TITLE
fun nas sync 不能上传本地的空目录

### ISSUE THREAD

**Issue by rsonghuster** [alibaba/funcraft#719]
比如  https://github.com/awesome-fc/customruntime-php/commit/fa7d09b8432f96754e33ee7b5c8db15c7b3eb039  我非要在文件夹下面弄一个空文件才会被上传到nas

有一些问题， 就是我要首先创建好这个目录， 不然可能有出现创建目录失败的权限问题

**Comment by tanhe123** [comment]
最新版本已经修复了这个问题
