### ISSUE TITLE
fun install 产生的 func-cache 问题

### ISSUE THREAD

**Issue by abersheeran** [alibaba/funcraft#726]
fun install 会建立 fun-cache 前缀的镜像，一开始我以为是可复用的，结果发现是 install 一次，新建一次。每个镜像都占大量空间。

不能在 install 完成后自动删掉这些镜像吗？256 GB 的小硬盘真心耗不起。

**Comment by abersheeran** [comment]
半年过去了？没有进展？

**Comment by guyskk** [comment]
`docker rmi --no-prune <ImageTag>` 用这个命令删除，既可以回收空间，又可以保留层给下次打包复用。
