### ISSUE TITLE
本地运行，服务内部重定向端口问题

### ISSUE THREAD

**Issue by wsw0108** [alibaba/funcraft#739]
即使用命令'fun local start'启动服务，fun显示服务监听主机8000端口。
而服务内部有http重定向的功能，结果就定向到服务端口为9000的URL上去了。

‘fun local start’启动的docker容器内有个环境变量FC_SERVER_PORT默认是9000。
这个该怎么设置呢？

**Comment by wsw0108** [comment]
补充：
是个SpringBoot的服务，application.yml里指定的服务端口是8085

**Comment by coco-super** [comment]
@wsw0108 为什么不能启动在 9000，会有什么问题吗？ 函数计算线上也是要求 9000 端口的。

**Comment by wsw0108** [comment]
@coco-super 试过改application.yml的端口到9000也不行的。从本地docker环境看，fc runtime应该是没有用application.yml里的server.port设置，直接监听了9000端口（只是加载了springboot应用Servlet代码？）。

然后我是从fc local start输出的地址（fc local固定的写死的8000端口）来访问服务的，但是服务里面有http重定向的代码，服务端只知道自己从9000端口收到了http请求，于是重定向url里的端口也是9000。

到了客户端浏览器这里，就访问不了docker里的9000端口了

**Comment by vangie** [comment]
@wsw0108 这里有个改端口的例子 https://github.com/awesome-fc/spring-petclinic-for-serverless/blob/master/bootstrap#L2

**Comment by wsw0108** [comment]
@vangie 这个是用的custom java runtime。虽然端口改成功了，但是依然没有改变fc local start固定监听8000端口的情况，所以我所描述的问题依然存在。这个应该得需要fc local知道本地docker里服务暴露的端口（如果写死9000的话，已经知道了）并做一些处理。
