### ISSUE TITLE
ReadTimeout(60000).

### ISSUE THREAD

**Issue by atonamy** [alibaba/funcraft#742]
When I trying to deploy my function using `fun deploy` I facing this issue:

```
Waiting for function query to be deployed...
                Waiting for packaging function query code...
                The function query has been packaged. A total of 1047 files files were compressed and the final size was 9.91 MB
ReadTimeout(60000). PUT https://XXXXXXXXXXXX.cn-zhangjiakou.fc.aliyuncs.com/XXX-XX-XX/services/XXX-XX/functions/query failed.
```

How to increase timeout option for deployment?

**Comment by tanhe123** [comment]
Use `fun config` to set `timeout` value or use `TIMEOUT=120 fun deploy` directly

**Comment by atonamy** [comment]
@tanhe123 thanks issue is resolved, but now I face another issue:

```
Waiting for service parisbejoux-cms-api to be deployed...
        Waiting for function query to be deployed...
                Waiting for packaging function query code...
                The function query has been packaged. A total of 5618 files files were compressed and the final size was 16.68 MB
PUT /services/parisbejoux-cms-api/functions/query failed with 400. requestid: 2a625666-c779-4ca5-9869-484b1d508740, message: Bad data in request body.
```
What's going wrong at this time?

**Comment by timeswind** [comment]
我把Timeout设成300秒deploy的时候还是会ReadTimeout

**Comment by timeswind** [comment]
把TIMEOUT设成1000后我也遇到“Bad data in request body”错误了

**Comment by tanhe123** [comment]
@timeswind  yml 内容是怎么写的，一般是类型不对导致的。可以发下脱敏的 yml 内容。

**Comment by timeswind** [comment]
@tanhe123

**Comment by timeswind** [comment]
我是按[](https://help.aliyun.com/document_detail/157692.html)这个教程做的

**Comment by tanhe123** [comment]
@timeswind 我测试了你的 yml 是没问题的，方便发下你的 fun 版本吗？以及能够复现的简单示例

**Comment by timeswind** [comment]
@tanhe123 3.6.7, 我完全是按上面发的doc链接做了一遍，会不会是因为我在美国的缘故

**Comment by tanhe123** [comment]
@timeswind 方便发下部署时使用的 region？以及报错的 requestId？

**Comment by timeswind** [comment]
@tanhe123 region: cn-hangzhou
报错没有显示requestId

**Comment by tanhe123** [comment]
@timeswind 哦，你说的 ReadTimeout 的问题，这个和你在国外有相关，你可以：
1. 通过 fun config 设置下超时时间
2. 如果依旧超时，建议使用国外的 region，可以通过 fun config 进行设置。你现在使用的是 cn-hangzhou 哈

**Comment by timeswind** [comment]
@tanhe123 我只是觉得有点奇怪 建立连接的延迟应该不影响上传吧

**Comment by tanhe123** [comment]
需要先建立链接才能上传哈。如果在国外，建议使用国外 region，如果还有问题，麻烦提新的 issue，这个 issue 先关闭了哈

**Comment by cnfi** [comment]
可以修改 fun 工具的部署时间，位置为 ~/.fcli/config.yaml ，在其中增加 timeout 字段。

`endpoint: ***************
api_version: '2016-08-15'
access_key_id: ***************
access_key_secret: ***************
security_token: ''
debug: false
timeout: 50      ## 部署超时时间，单位为 s
retries: 3`
