### ISSUE TITLE
fun nas sync命令， 当目录下文件数量过多时，会无法执行解压缩

### ISSUE THREAD

**Issue by shanjunf** [alibaba/funcraft#761]
原因是，在highWaterMark 默认数值是4096， 超过4096个文件，会异常

**Comment by shanjunf** [comment]
其中 const files = await readdirp.promise(dirPath, { type: 'files' }); 需要设置highWaterMark参数，才能支持超过4096个文件的上传解压

async function readDirRecursive(dirPath) {
  const files = await readdirp.promise(dirPath, { type: 'files' });
  const dirs = await readdirp.promise(dirPath, { type: 'directories' });

  const relativePaths = [];
  // windows 下需要将压缩文件路径住转换为 POXIS 路径
  if (process.platform === 'win32') {
    files.map(file => relativePaths.push((file.path).split(path.sep).join('/')));
    for (let dir of dirs) {
      if (await isEmptyDir(dir.fullPath)) {
        relativePaths.push(`${(dir.path).split(path.sep).join('/')}/`);
      }
    }
  } else {
    files.map(file => relativePaths.push(file.path));
    for (let dir of dirs) {
      if (await isEmptyDir(dir.fullPath)) {
        relativePaths.push(`${dir.path}/`);
      }
    }
  }
  return relativePaths;
}

**Comment by coco-super** [comment]
@shanjunf 是什么系统，ubuntu 吗？

**Comment by shanjunf** [comment]
mac下

**Comment by tanhe123** [comment]
```shell
or ((i=1; i<=100000; i++))
do
  echo $i > $i.txt
done
```

使用上面的命令创建了 100000 个小文件，测试是没问题的。

方便发下你的环境下的文件是怎么生成的吗？

**Comment by tanhe123** [comment]
这个问题最新版本应该已经修复了，如果还会遇到，麻烦提新的 issue
