### ISSUE TITLE
fun本地配置与控制台配置冲突提示

### ISSUE THREAD

**Issue by wuyeguangming** [alibaba/funcraft#763]
场景：由于控制台配置日志比较方便，因此我在控制配置好对应日志，但由于开发用fun，因此后面部署的时候没有同步日志的配置，并部署了本地的yml，导致控制台的日志配置被覆盖而失效
建议：本地yml在部署的时候判断下控制台的配置跟本地是否有冲突，如果有予以强提示

**Comment by tanhe123** [comment]
最新版本已经支持
