### ISSUE TITLE
ubuntu 上 fun deploy 报错

### ISSUE THREAD

**Issue by coco-super** [alibaba/funcraft#778]
Funfile：
```
RUNTIME python3
Run fun-install pip install alipay-sdk-python

```
fun install -> fun deploy 部署报错。
![image](https://user-images.githubusercontent.com/48934955/74667758-dbc60a00-51de-11ea-9229-cc1c822398bb.png)

**Comment by tangohu17** [comment]
怎么解决的，我也遇到同样的错误！
