### ISSUE TITLE
希望提供 fun export <service> <function> 导出配置的能力

### ISSUE THREAD

**Issue by JacksonTian** [alibaba/funcraft#791]
由于文档的不明确性，导致在编写 yaml 文件的时候会很迷糊，但控制台界面有很好的明确性，可以帮助填充一些配置信息。但下一次 fun deploy 就会冲掉控制台上的配置。

希望能通过导出配置，通过在本地 diff 的方式，明确如何填写详细的配置。

**Comment by tanhe123** [comment]
1. 现在可以通过控制台以及 vscode 插件导出。
2. 使用最新版本的 Fun，在部署时，会提示 diff，不会直接覆盖了

**Comment by kuafou** [comment]
同求。

虽然也可以通过其他方式导出，但是对于`funcraft`而言，这个工具本身是不完整的。

同时，能不能也加上`delete`，`list`等功能，像`kubectl`或`awscli`一样，提供一个完整的工具链~。
