### ISSUE TITLE
fun undeploy

### ISSUE THREAD

**Issue by roura356a** [alibaba/funcraft#80]
This is more a feature request. It would be nice to have a command like `fun undeploy` that basically does the opposite of `fun deploy`. Is a feature like that in plan?

**Comment by tanhe123** [comment]
If you deploy using ros, you can do this by removing the ros stack.
The documentation for ros deploy can be referenced:  https://yq.aliyun.com/articles/719104
If problems still exist, feel free to post a new issue.
