### ISSUE TITLE
fun deploy 后控制台设置的日志配置就失效了，需要重新配置

### ISSUE THREAD

**Issue by czjxy881** [alibaba/funcraft#813]
如题，能否提供日志配置yaml样例

**Comment by ChanDaoH** [comment]
fun 的服务配置在 deploy 时, 是以模板文件为准的, 如果没有定义则会清空. 这块需要比较好的提示

**Comment by tanhe123** [comment]
已经有了吧，使用最新版本就可以了。

日志配置可以参考：https://github.com/alibaba/funcraft/blob/master/docs/specs/2018-04-03-zh-cn.md#log-%E9%85%8D%E7%BD%AE%E5%AF%B9%E8%B1%A1

**Comment by tanhe123** [comment]
如果还有问题，可以提新的 issue。
