### ISSUE TITLE
支持安装字体

### ISSUE THREAD

**Issue by ChanDaoH** [alibaba/funcraft#822]
期望的使用体验:
1. 在代码目录新建一个 fonts 目录，然后复制所有字体到该目录即可。
2. 使用 fun deploy 进行部署。
3. 如果字体体积过大，则大依赖向导提示将字体放到 nas 并重新部署。

**Comment by philwu** [comment]
我一直都需要这个功能，因为运行环境没有太多中文字体，而且不能修改/etc/fonts/fonts.conf。一旦要处理PDF,word文档等功能的话，就会很麻烦。我现在只能在代码里从/code文件夹里动态载入我需要的字体，啧。

**Comment by tanhe123** [comment]
正在开发了，你可以先评估下上面的使用体验是不是符合你的预期。

**Comment by philwu** [comment]
windows下deploy失败，似乎是复制fonts.conf的路径不对
![无标题](https://user-images.githubusercontent.com/5704024/78852329-57199e80-7a5f-11ea-9b06-41b926565587.png)

**Comment by philwu** [comment]
> windows下deploy失败，似乎是复制fonts.conf的路径不对
> ![无标题](https://user-images.githubusercontent.com/5704024/78852329-57199e80-7a5f-11ea-9b06-41b926565587.png)

以上问题出现在用release页面下载的exe文件的时候，用npm安装的fun没有出现这个问题

**Comment by tanhe123** [comment]
@philwu 感谢反馈，我们看下这个问题

**Comment by coco-super** [comment]
@philwu 已确认问题，下个版本会修掉。
