### ISSUE TITLE
custom-springboot模版不支持用kotlin写的springboot

### ISSUE THREAD

**Issue by carlguo2016** [alibaba/funcraft#836]
执行fun local start后log显示程序跑起来，但是访问url却没有返回结果，log也没有显示接口访问的log

**Comment by tanhe123** [comment]
是端口没用 9000 吗

**Comment by carlguo2016** [comment]
&nbsp;是的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hehe Tan"<notifications@github.com&gt;; 
发送时间: 2020年4月1日(星期三) 下午4:38
收件人: "alibaba/funcraft"<funcraft@noreply.github.com&gt;; 
抄送: "花海"<285458125@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [alibaba/funcraft] custom-springboot模版不支持用kotlin写的springboot (#836)





 
是端口没用 9000 吗

**Comment by carlguo2016** [comment]
遇到个棘手问题，fun local start可运行，swgger和接口都执行完好，但是fun deploy以后，就不行了，我想问下是我服务器函数计算配置的问题么？本地swagger:&nbsp;http://localhost:8000/2016-08-15/proxy/FaasJava/api/swagger-ui.html
本地list接口:&nbsp;http://localhost:8000/2016-08-15/proxy/FaasJava/api/user/list?page=1&amp;limit=10


代码地址:&nbsp;https://github.com/carlguo2016/faas-java
函数计算域名对应如下图



报DomainRouteNotFound错：

麻烦有空看下，不胜感激！！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Hehe Tan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月1日(星期三) 下午4:38
收件人:&nbsp;"alibaba/funcraft"<funcraft@noreply.github.com&gt;;
抄送:&nbsp;"花海"<285458125@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/funcraft] custom-springboot模版不支持用kotlin写的springboot (#836)





 
是端口没用 9000 吗
