### ISSUE TITLE
custom-springboot如何自定义域名

### ISSUE THREAD

**Issue by carlguo2016** [alibaba/funcraft#839]
自定义域名如下：
<img width="787" alt="1" src="https://user-images.githubusercontent.com/14024243/78125674-ead9e200-7443-11ea-911a-e1945bdb2a43.png">

访问http://serverless.a-su.com.cn/springboot，404

**Comment by tanhe123** [comment]
如果路径配置的是 /springboot，那么传到 fc 上也会是 /springboot 。
可以先选择下面任意一个方案测试下：
1. 新建一个子域名给这个函数，然后将 /* 指向这个函数。
2. 设置 spring boot 的 context-path 配置为 /springboot

**Comment by carlguo2016** [comment]
谢谢
