### ISSUE TITLE
能否支持custom mock

### ISSUE THREAD

**Issue by Eronana** [alibaba/funcraft#873]
看代码, 目前是写死的
https://github.com/alibaba/funcraft/blob/1adbe015fdff0723d8d5e5c7db7cec76080087f5/src/lib/docker-opts.js#L252

相关问题: https://github.com/aliyun/fc-docker/issues/64

**Comment by tanhe123** [comment]
方便说下需求场景吗？想用这个特性做什么呢？

**Comment by Eronana** [comment]
> 方便说下需求场景吗？想用这个特性做什么呢？

就像是我在https://github.com/aliyun/fc-docker/issues/64中提到的, 自带`/var/fc/runtime/custom/mock`没有添加`x-fc-http-params`这个头.

然后就我目前的观察得知, 要想拿到path(而且不是有很多前缀的url), 似乎只能通过这个头来获取.

于是如果要用`fun local start`来本地调试的话, 就拿不到path和method.

顺便, 给我尝试了比较hack的方式, 的确能work.
```js
require('@alicloud/fun/lib/docker-opts').resolveMockScript = (runtime) => {
  return '/code/mock';
};
```
但是还有一些其他的不是很自由的小问题. 
于是现在正在尝试直接`docker run --rm -v $(pwd)/dist:/code -p 9000:9000 aliyunfc/runtime-custom`来本地调试..

不过我的这个提议和另一个repo里提到的问题, 我觉得你们可以考虑一下.
虽然我可能用不到了, 但是大概会帮助到后人吧.
