### ISSUE TITLE
执行fun build错误

### ISSUE THREAD

**Issue by end1314** [alibaba/funcraft#878]
按照帮助文档:
https://help.aliyun.com/document_detail/147039.html
执行操作后在fun build时报错
![image](https://user-images.githubusercontent.com/5654268/79832925-0306a680-83dd-11ea-901b-a72d8c2d1500.png)
![image](https://user-images.githubusercontent.com/5654268/79832947-0ef26880-83dd-11ea-9aba-1b7b7bba744a.png)
根据报错原因判断可能是因为mvn无法编译造成的...
调试mvn直到成功编译后,依然出现以上问题;
![image](https://user-images.githubusercontent.com/5654268/79833082-55e05e00-83dd-11ea-9772-736d655733b6.png)
求解答

**Comment by end1314** [comment]
@tanhe123 
此问题我也遇到了 , 同样的情况 ;
fun 3.6.10
maven 3.6.3

**Comment by tanhe123** [comment]
本周版本发布后，使用新版本即可。
