### ISSUE TITLE
函数java8编译出错

### ISSUE THREAD

**Issue by qianxingchuan** [alibaba/funcraft#881]
Hi，你好

根据阿里云的函数计算的官网的文档，通过fun init初始化一个helloworld的项目，然后执行 fun build，报错如图。
![image](https://user-images.githubusercontent.com/3124379/79869056-6b707a80-8413-11ea-9a34-7d16ff7e2e2f.png)

请帮忙看一下是否是哪个步骤操作出错

**Comment by tanhe123** [comment]
本周版本发布后，使用新版本即可。
