### ISSUE TITLE
funcraft源码开发调试

### ISSUE THREAD

**Issue by andyyin** [alibaba/funcraft#884]
有funcraft开发调试相关文档吗？

**Comment by tanhe123** [comment]
开发调试函数计算吗？可以参考这篇文档：https://help.aliyun.com/document_detail/146711.html

**Comment by andyyin** [comment]
不是，是开发调试funcraft的代码

**Comment by vangie** [comment]
@andyyin 您想为 funcraft 贡献代码么？

**Comment by tanhe123** [comment]
1. clone fun 到本地
2. npm install 安装所有依赖
3. 修改 src 下面的源码
4. npm run build 构建（使用 tsc -p ./ -w 自动编译也可以）
5. node bin/fun.js 测试

**Comment by andyyin** [comment]
> @andyyin 您想为 funcraft 贡献代码么？

是的呢，在学习中，后续可以贡献代码
