### ISSUE TITLE
docker中执行fun build失败

### ISSUE THREAD

**Issue by lumenghz** [alibaba/funcraft#890]
- fun版本号:
`3.6.10`
- 目录结构
  ```
  project
  │   Funfile
  │   template.yml
  ```
- 问题描述
我们想要在ci中自动执行`fun build`和`fun deploy`，ci的执行是在docker容器中的，当执行到`fun build`是出现了以下错误:
```shell
$ fun --version
3.6.10
$ fun build
using template: template.yml
start building function dependencies without docker
building service/method
Funfile exist, Fun will use container to build forcely
connect ENOENT /var/run/docker.sock
ERROR: Job failed: command terminated with exit code 1
 ```
  看描述似乎只要`Funfile`这个文件存在就是强制使用container去build，那如果我本身就是在container中去执行`fun build`的话，该怎么处理呢？或者如果本身我的执行方法是有问题的？

**Comment by TonySFU** [comment]
这个 fun build 会尝试访问 /var/run/docker.sock 去调用docker 帮助你本地调试。
所以你的机器上必须有个docker可以使用。
在container里面用`fun build` 的化，我的理解是你的container里面必须要有docker
