### ISSUE TITLE
[Bug] fun validate 无法对服务类型进行正确的提示

### ISSUE THREAD

**Issue by DevDengChao** [alibaba/funcraft#913]
![无法对服务的 Type 进行正确提示](https://user-images.githubusercontent.com/16363180/81786127-da805100-9531-11ea-900a-3e5469d639ba.png)

**Comment by wss-git** [comment]
![image](https://user-images.githubusercontent.com/56686088/86886933-607fd900-c12a-11ea-99c8-90b45375219d.png)
按照提供的已知信息没有复现，请问这个问题这边还能复现吗？

**Comment by DevDengChao** [comment]
3.6.14 版依然会出现这个问题.

![TIM截图20200708161403](https://user-images.githubusercontent.com/16363180/86895255-cd00d500-c136-11ea-815e-e651412b4ff7.png)

**Comment by wss-git** [comment]
![image](https://user-images.githubusercontent.com/56686088/87105722-5840ae80-c28e-11ea-881b-fc52f8986871.png)
![image](https://user-images.githubusercontent.com/56686088/87105732-5d9df900-c28e-11ea-8962-7a7a0fe69634.png)
![image](https://user-images.githubusercontent.com/56686088/87105743-61ca1680-c28e-11ea-8d2d-35a1f3491331.png)
![image](https://user-images.githubusercontent.com/56686088/87105752-668eca80-c28e-11ea-998c-df122ea97382.png)

修复后本地测试
