### ISSUE TITLE
[Feature] 建议 deploy 时允许只更新代码

### ISSUE THREAD

**Issue by XieEDeHeiShou** [alibaba/funcraft#916]
### 需求场景

很多时候服务与函数的配置在一开始的时候就确定好了, 稳定了不再变更了, 但是函数里的代码可能有新的需求或者 Bug 要修复, 这时就需要重新部署一次, 但是即使只更改 CodeUri 属性的值, 然后进行部署, fun 依然会提示需要对服务添加 Policies 以及修改 CodeUri.

### 预期行为

可以通过 `fun deploy --code-only service/function` 仅部署代码包.

![2020-05-16 23-43-39 的屏幕截图](https://user-images.githubusercontent.com/16363180/82124144-b346af80-97cf-11ea-9f24-a1e3fdd8aa70.png)

**Comment by coco-super** [comment]
@XieEDeHeiShou 这个表格 changes 有时不是很准确，你的目的是只更新 服务/函数 下的代码，现在fun deploy 是完全满足的，对于配置的覆盖（如果没有修改配置，自然不会改变）也没有什么体验上的影响。如果你想要只更新配置可以使用参数 --only-config

**Comment by XieEDeHeiShou** [comment]
网络不好的时候就会觉得没有影响但多余的操作就很讨人嫌。


 
---原始邮件---
发件人: "notifications"<notifications@github.com&gt;
发送时间: 2020年5月18日 18:55:19
收件人: "alibaba/funcraft"<funcraft@noreply.github.com&gt;;
抄送: "邓超"<2325690622@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [alibaba/funcraft] [Feature] 建议 deploy 时允许只更新代码 (#916)




 
@XieEDeHeiShou 这个表格 changes 有时不是很准确，你的目的是只更新 服务/函数 下的代码，现在fun deploy 是完全满足的，对于配置的覆盖（如果没有修改配置，自然不会改变）也没有什么体验上的影响。如果你想要只更新配置可以使用参数 --only-config
