### ISSUE TITLE
(HTTP code 400) unexpected - Dockerfile parse error line 2: unknown instruction: FUN-INSTALL

### ISSUE THREAD

**Issue by HelloValue** [alibaba/funcraft#919]
**fun install** 命令执行后报错.

----**Funfile**-----
RUNTIME python3
fun-install pip install psycopg2

----**.Funfile.generated.dockerfile**----
FROM registry.cn-beijing.aliyuncs.com/aliyunfc/runtime-python3.6:build-1.9.5
fun-install pip install psycopg2

-----**docker info**------
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 4
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-00155d010201
ID: 44YT:KQEB:DXIJ:EXPJ:C5AG:F7MZ:FWZM:E3OV:RNLZ:3SXG:64G5:7622
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 36
 System Time: 2020-05-19T09:44:17.9880085Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by coco-super** [comment]
@HelloValue Funfile 第二行 `RUN fun-install pip install psycopg2`

**Comment by coco-super** [comment]
@HelloValue Funfile 功能介绍 https://yq.aliyun.com/articles/719100
