### ISSUE TITLE
3.6.13版本创建函数挂载nas时出现了unzip错误

### ISSUE THREAD

**Issue by 2052874615** [alibaba/funcraft#939]
我在使用Funcraft3.6.13版本创建函数挂载nas时出现了unzip出错，我将版本回退到3.6.2错误就不报错了。

**Comment by coco-super** [comment]
@2052874615 能附上具体截图吗？

**Comment by 2052874615** [comment]
https://ticket.console.aliyun.com/attach/note_attach.do?id=80485898&order=0

https://ticket.console.aliyun.com/attach/note_attach.do?id=80485898&order=1

**Comment by coco-super** [comment]
@2052874615 错误截图就好，链接看不到

**Comment by 2052874615** [comment]
![note_attach](https://user-images.githubusercontent.com/58301023/83649221-883ec700-a5e9-11ea-8719-c63a2c4b2274.png)
![note_attach2](https://user-images.githubusercontent.com/58301023/83649249-8ecd3e80-a5e9-11ea-9c0b-521b22c6c064.png)

**Comment by coco-super** [comment]
@2052874615 这里修复了类似问题https://github.com/alibaba/funcraft/pull/936，不太确定是否覆盖您的场景，你加我钉钉沟通下吧 sunfeiyu136

**Comment by coco-super** [comment]
这里修复了类似问题 #https://github.com/alibaba/funcraft/pull/936，不太确定是否覆盖您的场景，你加我钉钉沟通下吧 sunfeiyu136

**Comment by coco-super** [comment]
这里修复了类似问题 #fixes https://github.com/alibaba/funcraft/pull/936，不太确定是否覆盖您的场景，你加我钉钉沟通下吧 sunfeiyu136

**Comment by coco-super** [comment]
@2052874615 这里修复了类似情况 https://github.com/alibaba/funcraft/pull/936，

**Comment by 2052874615** [comment]
目前我是把版本回退到了3.6.2，是没有问题了

**Comment by xxstop** [comment]
@One-YuTian 我也退回了3.6.2，没有上传的问题，但是缺少Patch请求，和nodejs版本无法选择12的问题。之前用的最新版本3.6.15
