### ISSUE TITLE
Parameter VSwitchId is mandatory for this action

### ISSUE THREAD

**Issue by momoca** [alibaba/funcraft#942]
Parameter VSwitchId is mandatory for this action., URL: http://nas.cn-shanghai.aliyuncs.com/
是什么问题？

**Comment by coco-super** [comment]
@momoca fun 的版本是多少

**Comment by momoca** [comment]
Release 3.6.13 @coco-super

**Comment by yingbiaoluo** [comment]
配置NasConfig: Auto，同碰到这个问题，fun版本号是3.6.13

**Comment by yingbiaoluo** [comment]
> @momoca fun 的版本是多少

同碰到这个问题（配置NasConfig: Auto，fun版本号是3.6.13）

**Comment by momoca** [comment]
@yingbiaoluo 和官方确认了.是版本bug,下个稍微老一点的吧.

**Comment by coco-super** [comment]
@momoca @yingbiaoluo 下个版本会修复

**Comment by momoca** [comment]
@coco-super 我说都出1个月了.啥时候修复呀

**Comment by wss-git** [comment]
> @coco-super 我说都出1个月了.啥时候修复呀

fun --version => 3.6.14

ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  node:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: 'helloworld'
      NasConfig: Auto
    node:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: nodejs8
        CodeUri: './'
      Events:
        httpTrigger:
          Type: HTTP
          Properties:
            AuthType: ANONYMOUS
            Methods: ['POST', 'GET']

这是我的 yml 模版，代码使用的 fun init nodejs8 的 http 触发器的示例没有复现你所说的问题，可以更具体一点吗？
